### ISSUE TITLE
Error Cannot read property 'scripts' of null after update

### ISSUE THREAD

**Issue by shareil23** [platformio/platformio-atom-ide-terminal#100]
how to fix this?

Cannot read property 'scripts' of null in C:\Users\Derandi Hermanda\.atom\packages\platformio-ide-terminal\package.json
Hide Stack Trace
TypeError: Cannot read property 'scripts' of null
    at normalize (C:\Users\Derandi Hermanda\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\normalize-package-data\lib\normalize.js:25:11)
    at PackageManager.module.exports.PackageManager.normalizePackageMetadata (C:\Users\Derandi Hermanda\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package-manager.js:727:16)
    at PackageManager.module.exports.PackageManager.loadPackageMetadata (C:\Users\Derandi Hermanda\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package-manager.js:701:18)
    at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\Derandi Hermanda\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package-manager.js:423:36)
    at C:\Users\Derandi Hermanda\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package-manager.js:402:19
    at Config.module.exports.Config.transact (C:\Users\Derandi Hermanda\AppData\Local\atom\app-1.11.2\resources\app.asar\src\config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (C:\Users\Derandi Hermanda\AppData\Local\atom\app-1.11.2\resources\app.asar\src\package-manager.js:397:19)
    at C:\Users\Derandi Hermanda\AppData\Local\atom\app-1.11.2\resources\app.asar\src\atom-environment.js:759:28
  at C:\Users\Derandi Hermanda\.atom\packages\platformio-ide-terminal\package.json:1:1

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js
