### ISSUE TITLE
Failed to activate the platformio-ide-terminal package

### ISSUE THREAD

**Issue by VigneshSambari** [platformio/platformio-atom-ide-terminal#1003]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.55.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: [platformio-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) package 2.10.1

### Stack Trace

Failed to activate the platformio-ide-terminal package

```
At Cannot find module 'atom-space-pen-views'
Require stack:
- C:\Users\Vignesh\.atom\packages\platformio-atom-ide-terminal-master\lib\status-bar.coffee
- C:\Users\Vignesh\.atom\packages\platformio-atom-ide-terminal-master\lib\platformio-ide-terminal.coffee
- C:\ProgramData\Vignesh\atom\app-1.55.0\resources\app.asar\static\index.html

Error: Cannot find module 'atom-space-pen-views'
Require stack:
- C:\Users\Vignesh\.atom\packages\platformio-atom-ide-terminal-master\lib\status-bar.coffee
- C:\Users\Vignesh\.atom\packages\platformio-atom-ide-terminal-master\lib\platformio-ide-terminal.coffee
- C:\ProgramData\Vignesh\atom\app-1.55.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Module._resolveFilename (C:/ProgramData/Vignesh/atom/app-1.55.0/resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.get_Module._resolveFilename (C:/ProgramData/Vignesh/atom/app-1.55.0/resources/app/static/<embedded>:11:155387)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (C:/ProgramData/Vignesh/atom/app-1.55.0/resources/app/static/<embedded>:11:146720)
    at /packages/platformio-atom-ide-terminal-master/lib/status-bar.coffee:2:13)
    at /packages/platformio-atom-ide-terminal-master/lib/status-bar.coffee:1:1)
    at /packages/platformio-atom-ide-terminal-master/lib/status-bar.coffee:1:1)
    at Module.get_Module._compile (C:/ProgramData/Vignesh/atom/app-1.55.0/resources/app/static/<embedded>:11:147404)
    at Object.value [as .coffee] (C:/ProgramData/Vignesh/atom/app-1.55.0/resources/app/static/<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (C:/ProgramData/Vignesh/atom/app-1.55.0/resources/app/static/<embedded>:11:146720)
    at Object.consumeStatusBar (/packages/platformio-atom-ide-terminal-master/lib/platformio-ide-terminal.coffee:28:27)
    at Provider.provide (C:/ProgramData/Vignesh/atom/app-1.55.0/resources/app/static/<embedded>:14:1093934)
    at ServiceHub.consume (C:/ProgramData/Vignesh/atom/app-1.55.0/resources/app/static/<embedded>:11:3492378)
    at Package.activateServices (C:/ProgramData/Vignesh/atom/app-1.55.0/resources/app/static/<embedded>:11:3500709)
    at Package.activateNow (C:/ProgramData/Vignesh/atom/app-1.55.0/resources/app/static/<embedded>:11:3497464)
    at C:/ProgramData/Vignesh/atom/app-1.55.0/resources/app/static/<embedded>:14:2607
    at Function.simpleDispatch (C:/ProgramData/Vignesh/atom/app-1.55.0/resources/app/static/<embedded>:11:1190181)
    at Emitter.emit (C:/ProgramData/Vignesh/atom/app-1.55.0/resources/app/static/<embedded>:11:1191622)
    at PackageManager.triggerDeferredActivationHooks (C:/ProgramData/Vignesh/atom/app-1.55.0/resources/app/static/<embedded>:11:384090)
    at C:/ProgramData/Vignesh/atom/app-1.55.0/resources/app/static/<embedded>:11:382841
    at TextEditorRegistry.updateAndMonitorEditorSettings (C:/ProgramData/Vignesh/atom/app-1.55.0/resources/app/static/<embedded>:11:512989)
```

### Commands

```
```

### Non-Core Packages

```
platformio-ide-terminal 2.10.1 
platomformio 0.7.1 
```

**Comment by UziTech** [comment]
This package is no longer maintained. Please uninstall platformio-ide-terminal and install either [terminus](https://atom.io/packages/terminus) or [x-terminal](https://atom.io/packages/x-terminal)

**Comment by abel12-tech** [comment]
my editor says failed to activate the terminal Please ,How can i fix this
