### ISSUE TITLE
Uncaught Error: Cannot find module '$ATOM_HOME/packages\platformio-ide-terminal\lib\process.coffe...

### ISSUE THREAD

**Issue by AkroutOmar** [platformio/platformio-atom-ide-terminal#1004]
[Enter steps to reproduce:]

1. Install platformio-atom-ide-terminal
2. Lanch terminal

**Atom**: 1.55.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Home
**Thrown From**: [platformio-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) package 2.10.1

### Stack Trace

Uncaught Error: Cannot find module 'C:\Users\omare\.atom\packages\platformio-ide-terminal\lib\process.coffee'
Require stack:
- C:\Users\omare\AppData\Local\atom\app-1.55.0\resources\app.asar\static\index.html

```
At internal/modules/cjs/loader.js:630

Error: Cannot find module 'C:\Users\omare\.atom\packages\platformio-ide-terminal\lib\process.coffee'
Require stack:
- C:\Users\omare\AppData\Local\atom\app-1.55.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.55.0/resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:155387)
    at Function.resolve (internal/modules/cjs/helpers.js:21:19)
    at Function.customRequire.resolve (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:14:5117984)
    at new Task (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:14:41575)
    at Function.Task.once (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:14:42482)
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.forkPtyProcess (/packages/platformio-ide-terminal/lib/view.coffee:250:19)
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.displayTerminal (/packages/platformio-ide-terminal/lib/view.coffee:265:30)
    at /packages/platformio-ide-terminal/lib/view.coffee:417:19
    at /packages/platformio-ide-terminal/lib/view.coffee:788:11)
    at HTMLDivElement.fn (/packages/platformio-ide-terminal/node_modules/jquery/dist/jquery.js:4855:19)
    at HTMLDivElement.dispatch (/packages/platformio-ide-terminal/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/platformio-ide-terminal/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -1:34.8.0 core:backspace (input.hidden-input)
     -1:28.3.0 core:undo (input.hidden-input)
     -0:24.4.0 platformio-ide-terminal:toggle (atom-pane.pane.active)
```

### Non-Core Packages

```
platformio-ide-terminal 2.10.1 
```

**Comment by UziTech** [comment]
This package is no longer maintained. Please uninstall platformio-ide-terminal and install either [terminus](https://atom.io/packages/terminus) or [x-terminal](https://atom.io/packages/x-terminal)
