### ISSUE TITLE
Uncaught TypeError: The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by john995x** [platformio/platformio-atom-ide-terminal#1010]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Education N
**Thrown From**: [platformio-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) package 2.10.1

### Stack Trace

Uncaught TypeError: The "path" argument must be of type string. Received type undefined

```
At internal/validators.js:112

TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112:11)
    at Object.resolve (path.js:139:9)
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.forkPtyProcess (/packages/platformio-ide-terminal/lib/view.coffee:127:25)
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.displayTerminal (/packages/platformio-ide-terminal/lib/view.coffee:136:20)
    at /packages/platformio-ide-terminal/lib/view.coffee:241:10
    at /packages/platformio-ide-terminal/lib/view.coffee:539:7)
    at HTMLDivElement.fn (/packages/platformio-ide-terminal/node_modules/jquery/dist/jquery.js:4855:19)
    at HTMLDivElement.dispatch (/packages/platformio-ide-terminal/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/platformio-ide-terminal/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
```

### Non-Core Packages

```
open-in-browsers 0.0.30 
platformio-ide-terminal 2.10.1 
```
### Comments:
# I was trying to change the path to within the 'Shell Override' setting so that I would be able to use 'bash' 
# shell on windows within atom instead of the standard 'cmd.exe' shell. 
# After changing the path to the location of the 'bash' executable inside of the 'Git' for Windows folder
# I received this error
#
#

**Comment by UziTech** [comment]
This package is no longer maintained. Please uninstall platformio-ide-terminal and install either [terminus](https://atom.io/packages/terminus) or [x-terminal](https://atom.io/packages/x-terminal)
