### ISSUE TITLE
Uncaught Error: Cannot find module '../src/term'Require stack:- $ATOM_HOME/packages\terminus\no...

### ISSUE THREAD

**Issue by Tayslaine** [platformio/platformio-atom-ide-terminal#1016]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: Unknown Windows version
**Thrown From**: [platformio-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) package 2.10.1

### Stack Trace

Uncaught Error: Cannot find module '../src/term'
Require stack:
- C:\Users\Sabrina\.atom\packages\terminus\node_modules\term.js\lib\index.js
- C:\Users\Sabrina\.atom\packages\terminus\node_modules\term.js\index.js
- C:\Users\Sabrina\.atom\packages\terminus\lib\view.js
- C:\Users\Sabrina\.atom\packages\terminus\lib\status-bar.js
- C:\Users\Sabrina\.atom\packages\terminus\lib\terminus.js
- C:\Users\Sabrina\AppData\Local\atom\app-1.57.0\resources\app.asar\static\index.html

```
At internal/modules/cjs/loader.js:800

Error: Cannot find module '../src/term'
Require stack:
- C:\Users\Sabrina\.atom\packages\terminus\node_modules\term.js\lib\index.js
- C:\Users\Sabrina\.atom\packages\terminus\node_modules\term.js\index.js
- C:\Users\Sabrina\.atom\packages\terminus\lib\view.js
- C:\Users\Sabrina\.atom\packages\terminus\lib\status-bar.js
- C:\Users\Sabrina\.atom\packages\terminus\lib\terminus.js
- C:\Users\Sabrina\AppData\Local\atom\app-1.57.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at o._resolveFilename (electron/js2c/renderer_init.js:43:689)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:157820)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:149153)
    at Function.Terminal (/packages/platformio-ide-terminal/node_modules/term.js/lib/index.js:48:27)
    at Function.getFocusedTerminal (/packages/terminus/lib/view.js:35:21)
    at handleBlur (/packages/terminus/lib/status-bar.js:118:37)
```

### Commands

```
 12x -1:20.7.0 core:move-down (div.terminus.status-bar)
     -1:06.2.0 core:move-up (div.panels-item)
     -1:01.2.0 core:move-left (div.package-detail)
  8x -1:00.1.0 core:move-down (div.package-detail)
```

### Non-Core Packages

```
atom-material-ui 2.1.3 
ide-html 0.7.0 
platformio-ide-terminal 2.10.1 
terminus 4.1.5 
```

**Comment by UziTech** [comment]
This package is no longer maintained. Please uninstall platformio-ide-terminal and install either [terminus](https://atom.io/packages/terminus) or [x-terminal](https://atom.io/packages/x-terminal)
