### ISSUE TITLE
Empty console in OsX El capitan 

### ISSUE THREAD

**Issue by Kliton** [platformio/platformio-atom-ide-terminal#131]
Atom version: 1.12.3
Package version: 2.2.2

When i click on "plus" button ( or when i use the command ) i always get a blank console with the blink cursor.

I have this error in logs

`task.coffee:86 Path must be a string. Received null TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.basename (path.js:1357:5)
    at Object.module.exports (/Users/kliton/.atom/packages/platformio-ide-terminal/lib/process.coffee:32:24)
    at process.<anonymous> (/private/var/folders/sc/7b8zrdl50tndgslkx5_dl_k00000gn/T/AppTranslocation/642A8C95-3A78-4376-BADA-7048AB70BD5D/d/Atom.app/Contents/Resources/app.asar/src/task-bootstrap.js:84:10)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:719:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)`

**Comment by cmenscher** [comment]
I am also seeing this in Atom 1.13.1, Package version 2.2.2.
