### ISSUE TITLE
Not working with Atom 1.14

### ISSUE THREAD

**Issue by Fred-Barclay** [platformio/platformio-atom-ide-terminal#155]
I haven't had a chance to test yet on other OSes/architectures, but pio-terminal isn't working on Atom 1.14.0-beta3 64-bit on Windows 7:
![atom-beta](https://i.imgur.com/dX20vnM.png)
There's just a blinking white cursor instead of a prompt - almost identical to the terminal-plus issue of a few months ago.

Steps to reproduce:
 * Install atom 1.14-beta 64bit on Windows (I also deleted the .atom config folder so I was starting with a clean slate).
 * `apm install platformio-ide-terminal`
 * Restart Atom and click on + (or `` ctrl-` ``)

**Comment by ivankravets** [comment]
I've just test on macOS and it works well. However, on Windows it doesn't work:

```
The system cannot find message text for message number 0x%1 in the message file for %2.
\\?\C:\Users\User\.atom\packages\platformio-ide-terminal\node_modules\pty.js\bin\win32\x64.m49.node Error: The system cannot find message text for message number 0x%1 in the message file for %2.
\\?\C:\Users\User\.atom\packages\platformio-ide-terminal\node_modules\pty.js\bin\win32\x64.m49.node
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:168:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:168:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\User\.atom\packages\platformio-ide-terminal\node_modules\pty.js\lib\pty.js:18:9)
    at Module._compile (module.js:556:32)
    at Object.value [as .js] (C:\Users\User\AppData\Local\atom\app-1.14.0-beta4\resources\app.asar\src\compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\User\.atom\packages\platformio-ide-terminal\node_modules\pty.js\lib\pty_win.js:10:36)
    at Module._compile (module.js:556:32)
    at Object.value [as .js] (C:\Users\User\AppData\Local\atom\app-1.14.0-beta4\resources\app.asar\src\compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\User\.atom\packages\platformio-ide-terminal\node_modules\pty.js\index.js:2:18)
    at Module._compile (module.js:556:32)
    at Object.value [as .js] (C:\Users\User\AppData\Local\atom\app-1.14.0-beta4\resources\app.asar\src\compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)(anonymous function) @ task.coffee:86(anonymous function) @ task.coffee:146module.exports.Emitter.simpleDispatch @ C:\Users\User\AppData\Local\atom\app-1.14.0-beta4\resources\app.asar\node_modules\event-kit\lib\emi…:25module.exports.Emitter.emit @ C:\Users\User\AppData\Local\atom\app-1.14.0-beta4\resources\app.asar\node_modules\event-kit\lib\emi…:129(anonymous function) @ task.coffee:98emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
```

@Tyriar, could you point me what should be changed? I see that you [switched PTY.JS to TS](https://github.com/Tyriar/node-pty). Would be thankful for any help.

**Comment by Tyriar** [comment]
Looks like something bad happened during compilation, maybe some module/node version in apm/atom changed?

**Comment by ivankravets** [comment]
@Tyriar I used Atom's node/apm/npm to build a binary. I've just shared [whole build process on AppVeyor](https://ci.appveyor.com/project/ivankravets/pty-js-bin). Also, binaries are available as "artifacts". See https://ci.appveyor.com/project/ivankravets/pty-js-bin/build/artifacts

Would be good to find maintainers who will support this package. I see that there is no alternative to this package in Atom registry and thousands of developers use it.

@nathansobo, @as-cii could you explain to us what has been changed significantly in Atom 1.14? Thank you!

**Comment by nikolaiborisik** [comment]
Atom 1.14 was released. Terminal works fine on WIndows Atom 1.14 ia32, but not on x64. Any chance to fix?

**Comment by zorn-v** [comment]
Use this binaries https://github.com/platformio/pty.js/pull/1
Put it to ~\\.atom\packages\platformio-ide-terminal\node_modules\pty.js\bin\win32\

**Comment by joshuadavidson** [comment]
Thanks @zorn-v. Placing those files worked for me. Hopefully your changes get incorporated quickly.

**Comment by a1ly404** [comment]
Worked for me as well, I just had to drop them into that folder without overriding anything and relaunched atom. Thanks @zorn-v

**Comment by ivankravets** [comment]
Please update `platformio-ide-terminal` to 2.2.3.

P.S: Thanks a lot, @zorn-v 👍
