### ISSUE TITLE
New Terminal Crashes - for the platformio-ide-terminal installed for Atom IDE

### ISSUE THREAD

**Issue by vignesh-r** [platformio/platformio-atom-ide-terminal#161]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.13.1
**Electron Version**: 1.3.13
**System**: Microsoft Windows 10 Enterprise Insider Preview
**Thrown From**: [platformio-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) package, v2.2.2

### Stack Trace

Uncaught Error: channel closed

```
At events.js:160

Error: channel closed
    at ChildProcess.target.send (internal/child_process.js:540:16)
    at Task.module.exports.Task.send (C:\Users\vigneshr\AppData\Local\atom\app-1.13.1\resources\app.asar\src\task.js:117:27)
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.input (file:///C:/Users/vigneshr/.atom/packages/platformio-ide-terminal/lib/view.coffee:262:17)
    at Terminal.<anonymous> (file:///C:/Users/vigneshr/.atom/packages/platformio-ide-terminal/lib/view.coffee:141:8)
    at Terminal.EventEmitter.emit (C:\Users\vigneshr\.atom\packages\platformio-ide-terminal\node_modules\term.js\src\term.js:109:12)
    at Terminal.handler (C:\Users\vigneshr\.atom\packages\platformio-ide-terminal\node_modules\term.js\src\term.js:3493:8)
    at C:\Users\vigneshr\.atom\packages\platformio-ide-terminal\node_modules\term.js\src\term.js:3253:12
```

### Commands

```
     -1:42.4.0 editor:consolidate-selections (input.hidden-input)
     -1:42.4.0 core:cancel (input.hidden-input)
     -1:42.3.0 editor:consolidate-selections (input.hidden-input)
     -1:42.3.0 core:cancel (input.hidden-input)
     -1:39.5.0 editor:consolidate-selections (input.hidden-input)
     -1:39.5.0 core:cancel (input.hidden-input)
     -1:39.3.0 editor:consolidate-selections (input.hidden-input)
     -1:39.3.0 core:cancel (input.hidden-input)
     -1:39.1.0 editor:consolidate-selections (input.hidden-input)
     -1:39.1.0 core:cancel (input.hidden-input)
     -1:37 editor:consolidate-selections (input.hidden-input)
     -1:37 core:cancel (input.hidden-input)
     -0:59.9.0 terminal-plus:new (input.hidden-input)
     -0:42.3.0 line-ending-selector:show (atom-text-editor.editor.is-focused)
     -0:37.9.0 grammar-selector:show (atom-text-editor.editor)
  2x -0:30.1.0 platformio-ide-terminal:new (textarea.)
```

### Config

```json
{
  "core": {
    "telemetryConsent": "limited",
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
platformio-ide-terminal, v2.2.2 (active)
terminal-plus, v0.14.5 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (inactive)
one-light-ui, v1.8.2 (active)
one-dark-syntax, v1.6.0 (inactive)
one-light-syntax, v1.6.0 (active)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.3 (active)
metrics, v1.1.3 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by the-j0k3r** [comment]
duplicate of #556 @ivankravets please close
