### ISSUE TITLE
Uncaught Error: Cannot find module '../src/term'

### ISSUE THREAD

**Issue by lifeiscontent** [platformio/platformio-atom-ide-terminal#187]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [platformio-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) package 2.4.0

### Stack Trace

Uncaught Error: Cannot find module '../src/term'

```
At module.js:457

Error: Cannot find module '../src/term'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Function.Terminal (/packages/platformio-ide-terminal/node_modules/term.js/lib/index.js:48:27)
    at Function.module.exports.PlatformIOTerminalView.getFocusedTerminal (/packages/platformio-ide-terminal/lib/view.coffee:122:22)
    at /packages/platformio-ide-terminal/lib/status-bar.coffee:285:49
```

### Commands

```
  2x -0:39.4.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:32.7.0 editor:newline (input.hidden-input)
  3x -0:32.3.0 core:backspace (input.hidden-input)
     -0:28.8.0 core:select-all (input.hidden-input)
     -0:28.4.0 command-palette:toggle (input.hidden-input)
     -0:27.4.0 core:confirm (input.hidden-input)
     -0:27.4.0 sort-lines:sort (input.hidden-input)
     -0:26.9.0 core:save (input.hidden-input)
     -0:10.8.0 core:close (input.hidden-input)
```

### Non-Core Packages

```
atom-ternjs 0.18.2 
autocomplete-ruby 0.2.6 
browser-plus 0.0.87 
color-picker 2.2.5 
emmet 2.4.3 
file-icons 2.0.17 
git-plus 7.3.3 
language-babel 2.56.0 
language-rspec 0.5.1 
linter 1.11.23 
linter-eslint 8.1.2 
merge-conflicts 1.4.4 
minimap 4.26.8 
pigments 0.39.0 
platformio-ide-terminal 2.4.0 
project-manager 3.3.3 
ruby-test 1.0.1 
script 3.14.1 
sort-lines 0.14.0 
todo-show 1.11.0 
```

**Comment by Gamez93** [comment]
i have the same problem...

**Comment by the-j0k3r** [comment]
Please retest with platformio-ide-terminal 2.9.0
