### ISSUE TITLE
Uncaught Error: Cannot find module '$ATOM_HOME/packages\platformio-ide-terminal\lib\process.coffee'

### ISSUE THREAD

**Issue by evijay** [platformio/platformio-atom-ide-terminal#190]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 ia32
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [platformio-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) package 2.5.0

### Stack Trace

Uncaught Error: Cannot find module 'C:\Users\ViJaY\.atom\packages\platformio-ide-terminal\lib\process.coffee'

```
At module.js:457

Error: Cannot find module 'C:\Users\ViJaY\.atom\packages\platformio-ide-terminal\lib\process.coffee'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.15.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.require.resolve (/app.asar/src/native-compile-cache.js:53:23)
    at /app.asar/src/task.js:35:26)
    at Function.module.exports.Task.once (/app.asar/src/task.js:17:14)
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.forkPtyProcess (/packages/platformio-ide-terminal/lib/view.coffee:233:19)
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.displayTerminal (/packages/platformio-ide-terminal/lib/view.coffee:248:30)
    at /packages/platformio-ide-terminal/lib/view.coffee:400:19
    at /packages/platformio-ide-terminal/lib/view.coffee:718:11)
    at HTMLDivElement.fn (/packages/platformio-ide-terminal/node_modules/jquery/dist/jquery.js:4855:19)
    at HTMLDivElement.dispatch (/packages/platformio-ide-terminal/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/platformio-ide-terminal/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -0:18.2.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
atom-formatter-jsbeautify 1.1.2 
atom-prettify 0.1.3 
autoclose-tags 0.2.1 
color-picker 2.2.5 
emmet 2.4.3 
formatter-jsbeautify 1.0.2 
platformio-ide-terminal 2.5.0 
terminal-plus 0.14.5 
```

**Comment by abhishekthakur7** [comment]
any solution to this issue ?

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js

if issues persist open a new ticket with required information.

Thx =)
