### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received ~

### ISSUE THREAD

**Issue by kisyular** [platformio/platformio-atom-ide-terminal#199]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [platformio-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) package 2.5.0

### Stack Trace

Uncaught TypeError: Path must be a string. Received undefined

```
At path.js:7

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:1148:7)
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.forkPtyProcess (/packages/platformio-ide-terminal/lib/view.coffee:110:25)
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.displayTerminal (/packages/platformio-ide-terminal/lib/view.coffee:119:20)
    at /packages/platformio-ide-terminal/lib/view.coffee:224:10
    at /packages/platformio-ide-terminal/lib/view.coffee:488:7)
    at HTMLDivElement.fn (/packages/platformio-ide-terminal/node_modules/jquery/dist/jquery.js:4855:19)
    at HTMLDivElement.dispatch (/packages/platformio-ide-terminal/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/platformio-ide-terminal/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
```

### Non-Core Packages

```
atom-autocomplete-php 0.22.2 
atom-beautify 0.29.17 
atom-bootstrap3 1.2.12 
atom-html-preview 0.1.22 
atom-python-run 0.7.3 
atom-ternjs 0.18.2 
auto-indent 0.5.0 
autoclose-html 0.23.0 
autocomplete-clang 0.10.0 
autocomplete-js-import 1.4.0 
autocomplete-modules 1.6.8 
autocomplete-python 1.8.62 
build 0.67.0 
busy 0.7.0 
busy-signal 1.3.0 
close-tags 0.6.0 
git-time-machine 1.5.6 
intentions 1.1.2 
kite 0.18.0 
language-ini 1.19.0 
linter 2.1.1 
linter-gcc 0.7.1 
linter-htmlhint 1.3.2 
linter-js-standard 3.9.0 
linter-stylelint 3.9.0 
linter-ui-default 1.2.1 
php-cs-fixer 4.1.0 
pigments 0.39.1 
platformio-ide-terminal 2.5.0 
python-indent 1.0.2 
script-runner 2.1.1 
```

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js
