### ISSUE TITLE
Failed to activate the platformio-ide-terminal package

### ISSUE THREAD

**Issue by dixonwille** [platformio/platformio-atom-ide-terminal#22]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.7.2
**System**: Microsoft Windows 10 Pro
**Thrown From**: [platformio-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) package, v2.0.9
### Stack Trace

Failed to activate the platformio-ide-terminal package

```
At Path must be a string. Received undefined

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.win32.resolve (path.js:130:5)
    at file:///C:/Users/willd/.atom/packages/platformio-ide-terminal/lib/platformio-ide-terminal.coffee:71:20
    at Object.<anonymous> (file:///C:/Users/willd/.atom/packages/platformio-ide-terminal/lib/platformio-ide-terminal.coffee:68:20)
    at Object.<anonymous> (file:///C:/Users/willd/.atom/packages/platformio-ide-terminal/lib/platformio-ide-terminal.coffee:1:1)
    at Module._compile (C:\Users\willd\AppData\Local\atom\app-1.7.2\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\willd\AppData\Local\atom\app-1.7.2\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\willd\AppData\Local\atom\app-1.7.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\willd\AppData\Local\atom\app-1.7.2\resources\app.asar\src\package.js:715:27)
    at Package.module.exports.Package.activateNow (C:\Users\willd\AppData\Local\atom\app-1.7.2\resources\app.asar\src\package.js:173:16)
    at C:\Users\willd\AppData\Local\atom\app-1.7.2\resources\app.asar\src\package.js:156:32
    at Package.module.exports.Package.measure (C:\Users\willd\AppData\Local\atom\app-1.7.2\resources\app.asar\src\package.js:92:15)
    at C:\Users\willd\AppData\Local\atom\app-1.7.2\resources\app.asar\src\package.js:149:26
    at Package.module.exports.Package.activate (C:\Users\willd\AppData\Local\atom\app-1.7.2\resources\app.asar\src\package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\willd\AppData\Local\atom\app-1.7.2\resources\app.asar\src\package-manager.js:538:21)
    at C:\Users\willd\AppData\Local\atom\app-1.7.2\resources\app.asar\src\package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (C:\Users\willd\AppData\Local\atom\app-1.7.2\resources\app.asar\src\config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (C:\Users\willd\AppData\Local\atom\app-1.7.2\resources\app.asar\src\package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (C:\Users\willd\AppData\Local\atom\app-1.7.2\resources\app.asar\src\package-manager.js:497:46)
    at C:\Users\willd\AppData\Local\atom\app-1.7.2\resources\app.asar\src\atom-environment.js:754:28
```
### Commands

```
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
autocomplete-go, v1.0.6
builder-go, v1.0.0
environment, v1.2.0
file-icons, v1.7.7
go-config, v1.1.4
go-get, v1.0.3
go-plus, v4.1.0
gofmt, v1.1.6
gometalinter-linter, v1.1.0
gorename, v1.0.2
imdone-atom, v1.3.29
imdone-atom-github, v0.1.11
linter, v1.11.4
merge-conflicts, v1.4.2
minimap, v4.23.0
navigator-godef, v1.0.3
platformio-ide-terminal, v2.0.9
project-manager, v2.9.7
tester-go, v1.0.4

# Dev
No dev packages
```
##

**Comment by sjeeva** [comment]
having same issue

**Comment by zzz0906** [comment]
Ditto

**Comment by flakfire** [comment]
same here

**Comment by enricopesce** [comment]
same

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.2 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [platformio-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) package 2.5.5


### Stack Trace

Failed to activate the platformio-ide-terminal package

```
At Cannot find module './status-bar'

Error: Cannot find module './status-bar'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at Object.consumeStatusBar (/packages/platformio-ide-terminal/lib/platformio-ide-terminal.coffee:55:40)
    at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app/node_modules/service-hub/lib/provider.js:34:58)
    at ServiceHub.module.exports.ServiceHub.consume (/Applications/Atom.app/Contents/Resources/app/node_modules/service-hub/lib/service-hub.js:50:24)
    at Package.module.exports.Package.activateServices (/Applications/Atom.app/Contents/Resources/app/src/package.js:454:81)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:256:22)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:1014:34
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PackageManager.module.exports.PackageManager.triggerDeferredActivationHooks (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:676:42)
    at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:607:23
```

### Commands

```
```

### Non-Core Packages

```
indent-guide-improved 1.4.13 
language-docker 1.1.8 
markdown-preview-plus 2.4.10 
platformio-ide-terminal 2.5.5 
split-diff 1.5.1 
```

**Comment by the-j0k3r** [comment]
retry again with 2.9.0
