### ISSUE TITLE
Uncaught Error: spawn UNKNOWN

### ISSUE THREAD

**Issue by djwoods154** [platformio/platformio-atom-ide-terminal#220]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [platformio-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) package 2.5.0

### Stack Trace

Uncaught Error: spawn UNKNOWN

```
At internal/child_process.js:313

Error: spawn UNKNOWN
    at exports._errnoException (util.js:1026:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:392:9)
    at Object.exports.fork (child_process.js:70:10)
    at /app.asar/src/task.js:41:40)
    at Function.module.exports.Task.once (/app.asar/src/task.js:17:14)
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.forkPtyProcess (/packages/platformio-ide-terminal/lib/view.coffee:110:10)
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.displayTerminal (/packages/platformio-ide-terminal/lib/view.coffee:119:20)
    at /packages/platformio-ide-terminal/lib/view.coffee:224:10
    at /packages/platformio-ide-terminal/lib/view.coffee:488:7)
    at HTMLDivElement.fn (/packages/platformio-ide-terminal/node_modules/jquery/dist/jquery.js:4855:19)
    at HTMLDivElement.dispatch (/packages/platformio-ide-terminal/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/platformio-ide-terminal/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
  2x -3:34.8.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-shell-commands 1.5.0 
autocomplete-html-entities 0.1.0 
build 0.67.0 
build-powershell 0.10.1 
busy 0.7.0 
html-head-snippets 0.2.0 
html-outliner 0.1.1 
html-template-generator 0.3.0 
html-to-css 0.2.2 
language-powershell 4.0.0 
make-html-code 1.4.0 
open-html-in-browser 0.1.0 
platformio-ide-terminal 2.5.0 
power-editor 0.2.0 
script 3.14.1 
Stringify-Html 0.0.2 
```

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js
