### ISSUE TITLE
Platform-Ide-Terminal Not Installed

### ISSUE THREAD

**Issue by GeoJetta** [platformio/platformio-atom-ide-terminal#222]
When attempting to install platform-ide-terminal, atom pops up a window stating 
`These packages were not installed, check your console for more info: -platform-ide-terminal`
No more information is given in the terminal. When I attempt to install again by searching the package, the blue "install" button looks to be loading but never does anything. When I install through `apm install platform-ide-terminal`, it takes a few seconds, then returns `undefined` and exits installation, without further information.
I'm running atom 1.16.0 on Ubuntu Xenial. Is there any way I can get an indication of where the problem lies?
Update: When I try to use `sudo` with install, this happens. Not sure if this is just a thing with `apm`, though.
```
Installing platformio-ide-terminal to /home/ntrc/.atom/packages ���

> pty.js@0.3.0 install /tmp/apm-install-dir-11743-6205-1e93mef.mm3zlx47vi/node_modules/platformio-ide-terminal/node_modules/pty.js
> node scripts/install.js

/tmp/apm-install-dir-11743-6205-1e93mef.mm3zlx47vi
��������� (empty)


module.js:471
    throw err;
    ^

Error: Cannot find module '/tmp/apm-install-dir-11743-6205-1e93mef.mm3zlx47vi/node_modules/platformio-ide-terminal/node_modules/pty.js/scripts/install.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-11743-6205-1e93mef.mm3zlx47vi/package.json'
npm WARN apm-install-dir-11743-6205-1e93mef.mm3zlx47vi No description
npm WARN apm-install-dir-11743-6205-1e93mef.mm3zlx47vi No repository field.
npm WARN apm-install-dir-11743-6205-1e93mef.mm3zlx47vi No README data
npm WARN apm-install-dir-11743-6205-1e93mef.mm3zlx47vi No license field.
npm ERR! Linux 3.18.0-13759-g98e7e0e
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/ntrc/.atom/.apm/.apmrc" "--userconfig" "/home/ntrc/.atom/.apmrc" "install" "/tmp/d-11743-6205-1bqfslo.zg2xa8aor/package.tgz" "--runtime=electron" "--target=1.3.13" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.3.0 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.3.0 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pty.js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-11743-6205-1e93mef.mm3zlx47vi/npm-debug.log
npm ERR! code 1
```
Update 2: Using the `--verbose` command, I came up with these errors before it stated `undefined`
```
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-11743-11471-17jy60.1ixsazia4i/package.json'
npm WARN apm-install-dir-11743-11471-17jy60.1ixsazia4i No description
npm WARN apm-install-dir-11743-11471-17jy60.1ixsazia4i No repository field.
npm WARN apm-install-dir-11743-11471-17jy60.1ixsazia4i No README data
npm WARN apm-install-dir-11743-11471-17jy60.1ixsazia4i No license field.
```
Seems as though I am missing `/tmp/apm-install-dir-11743-11471-17jy60.1ixsazia4i/package.json`

**Comment by GeoJetta** [comment]
Solved by cloning, linking, and installing.
`git clone https://github.com/platformio/platformio-atom-ide-terminal.git`
`apm link <path to cloned repository>`
(while in directory of cloned repository) `apm install`
