### ISSUE TITLE
Uncaught Error: Cannot find module './input-dialog'

### ISSUE THREAD

**Issue by xcsweb** [platformio/platformio-atom-ide-terminal#228]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [platformio-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) package 2.5.0

### Stack Trace

Uncaught Error: Cannot find module './input-dialog'

```
At C:\Users\Administrator\AppData\Local\atom\app-1.17.0\resources\app\static\<embedded>:1

Error: Cannot find module './input-dialog'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.17.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.17.0/resources/app/src/module-cache.js:354:1)
    at Module.require (~/AppData/Local/atom/app-1.17.0/resources/app/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.17.0/resources/app/src/native-compile-cache.js:66:1)
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.inputDialog (/packages/platformio-ide-terminal/lib/view.coffee:727:23)
    at /packages/file-icon-supplement/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLButtonElement.dispatch (/packages/file-icon-supplement/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/packages/file-icon-supplement/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -9:31.3.0 core:paste (div.line)
     -9:29.3.0 core:confirm (input.hidden-input)
  2x -7:48.3.0 platformio-ide-terminal:toggle (div.panels-item)
  2x -3:19.3.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -3:07.4.0 intentions:highlight (input.hidden-input)
     -3:07.0 editor:toggle-line-comments (input.hidden-input)
     -3:06.7.0 core:save (input.hidden-input)
     -3:03.5.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
 11x -1:36 platformio-ide-terminal:toggle (button.btn.icon.enablement.icon-playback-pause)
```

### Non-Core Packages

```
activate-power-mode 1.4.0 
atom-ternjs 0.18.3 
autocomplete-paths 1.0.5 
autoprefixer 3.7.0 
busy-signal 1.4.1 
emmet 2.4.3 
file-icons 2.1.5 
intentions 1.1.2 
language-vue 0.21.2 
minimap 4.28.2 
platformio-ide-terminal 2.5.0 
simplified-chinese-menu 5.3.1 
terminal-plus 0.14.5 
```

**Comment by Sangeeta-Singh** [comment]
I am also having same issue, is there something to resolve this...?

**Comment by JeremyLG** [comment]
I just got this issue when upgrading to 2.9.0 from 2.8.0, anyone ?

**Comment by the-j0k3r** [comment]
uninstall and reinstall after resetting atom to defaults.

**Comment by the-j0k3r** [comment]
Reading error seems unrelated to platformio-ide-terminal. So retry again with Atom reset. Else open a new bug report with full information.
