### ISSUE TITLE
Uncaught Error: Cannot find module '../src/term'

### ISSUE THREAD

**Issue by somaiahk** [platformio/platformio-atom-ide-terminal#245]
C:\Users\somaiah\AppData\Local\atom\app-1.17.2\resources\app\static\<embedded>:1
Hide Stack Trace
Error: Cannot find module '../src/term'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (C:\Users\somaiah\AppData\Local\atom\app-1.17.2\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (C:\Users\somaiah\AppData\Local\atom\app-1.17.2\resources\app\src\module-cache.js:354:1)
    at Module.require (file:///C:/Users/somaiah/AppData/Local/atom/app-1.17.2/resources/app/static/index.js:40:43)
    at require (C:\Users\somaiah\AppData\Local\atom\app-1.17.2\resources\app\src\native-compile-cache.js:66:1)
    at Function.Terminal (C:\Users\somaiah\.atom\packages\platformio-ide-terminal\node_modules\term.js\lib\index.js:48:27)
    at Function.module.exports.PlatformIOTerminalView.getFocusedTerminal (C:\Users\somaiah\.atom\packages\platformio-ide-terminal\lib\view.coffee:122:22)
    at C:\Users\somaiah\.atom\packages\platformio-ide-terminal\lib\status-bar.coffee:285:49
The error was thrown from the platformio-ide-terminal package. This issue has already been reported.

**Comment by karanjariwala** [comment]
+1

**Comment by akash2016** [comment]
+1

**Comment by EmilianoCostantini** [comment]
+1

**Comment by TheHunterDog** [comment]
+1

**Comment by nitdevv** [comment]
+1

**Comment by nitdevv** [comment]
+1

**Comment by adeelahmadk** [comment]
+1

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js
