### ISSUE TITLE
Uncaught TypeError: Cannot set property '0' of undefined

### ISSUE THREAD

**Issue by igorhaf** [platformio/platformio-atom-ide-terminal#248]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Ubuntu 16.04.2
**Thrown From**: [platformio-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) package 2.5.1

### Stack Trace

Uncaught TypeError: Cannot set property '0' of undefined

```
At /home/cliksocial/.atom/packages/platformio-ide-terminal/node_modules/term.js/src/term.js:1939

TypeError: Cannot set property '0' of undefined
    at Terminal.write (/packages/platformio-ide-terminal/node_modules/term.js/src/term.js:1939:55)
    at /packages/platformio-ide-terminal/lib/view.coffee:134:17
    at /opt/atom/resources/app/src/task.js:128:1
    at Function.module.exports.Emitter.simpleDispatch (/opt/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (/opt/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:1)
    at ChildProcess.<anonymous> (/opt/atom/resources/app/src/task.js:80:1)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
  2x -9:11.7.0 editor:newline (input.hidden-input)
     -9:11.2.0 core:paste (input.hidden-input)
     -9:10.6.0 core:save (input.hidden-input)
     -6:33.7.0 core:paste (input.hidden-input)
     -6:33 core:save (input.hidden-input)
     -6:10.1.0 core:paste (input.hidden-input)
     -6:09.7.0 core:save (input.hidden-input)
     -6:08.8.0 core:undo (input.hidden-input)
     -6:02.6.0 core:paste (input.hidden-input)
  3x -6:01.1.0 core:save (input.hidden-input)
     -5:45.7.0 core:paste (input.hidden-input)
     -5:45.3.0 core:save (input.hidden-input)
     -5:36.4.0 core:backspace (input.hidden-input)
     -5:34.8.0 core:save (input.hidden-input)
     -3:06.4.0 core:paste (input.hidden-input)
  3x -3:05.6.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
platformio-ide-terminal 2.5.1 
```

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js
