### ISSUE TITLE
Uncaught TypeError: Cannot set property '0' of undefined

### ISSUE THREAD

**Issue by david-byng** [platformio/platformio-atom-ide-terminal#25]
[Enter steps to reproduce below:]
1. open tmux
2. scroll up
3. resize the terminal window

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.4
**Thrown From**: [platformio-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) package, v2.0.9
### Stack Trace

Uncaught TypeError: Cannot set property '0' of undefined

```
At /Users/davidgodfrey/.atom/packages/platformio-ide-terminal/node_modules/term.js/src/term.js:3436

TypeError: Cannot set property '0' of undefined
    at Terminal.eraseRight (/Users/davidgodfrey/.atom/packages/platformio-ide-terminal/node_modules/term.js/src/term.js:3436:13)
    at Terminal.eraseInLine (/Users/davidgodfrey/.atom/packages/platformio-ide-terminal/node_modules/term.js/src/term.js:3677:12)
    at Terminal.write (/Users/davidgodfrey/.atom/packages/platformio-ide-terminal/node_modules/term.js/src/term.js:2348:18)
    at /Users/davidgodfrey/.atom/packages/platformio-ide-terminal/lib/view.coffee:133:17
    at /Applications/Atom.app/Contents/Resources/app.asar/src/task.js:126:25
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/task.js:78:34)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:686:10)
    at Pipe.channel.onread (internal/child_process.js:440:11)
```
### Commands

```
  2x -0:26.4.0 editor:select-to-end-of-word (atom-text-editor.editor.power-mode.is-focused)
     -0:24.2.0 autocomplete-plus:confirm (atom-text-editor.editor.power-mode.is-focused.autocomplete-active)
     -0:23.5.0 core:move-right (atom-text-editor.editor.power-mode.is-focused)
     -0:23.3.0 editor:select-to-end-of-line (atom-text-editor.editor.power-mode.is-focused)
     -0:23 core:backspace (atom-text-editor.editor.power-mode.is-focused)
     -0:19.8.0 editor:delete-to-beginning-of-word (atom-text-editor.editor.power-mode.is-focused.autocomplete-active)
  2x -0:16.4.0 core:backspace (atom-text-editor.editor.power-mode.is-focused)
     -0:14 autocomplete-plus:cancel (atom-text-editor.editor.power-mode.is-focused.autocomplete-active)
     -0:13.7.0 editor:select-to-first-character-of-line (atom-text-editor.editor.power-mode.is-focused)
     -0:13.6.0 core:move-left (atom-text-editor.editor.power-mode.is-focused)
  4x -0:13.3.0 editor:move-to-end-of-word (atom-text-editor.editor.power-mode.is-focused)
     -0:12.3.0 editor:select-to-end-of-word (atom-text-editor.editor.power-mode.is-focused)
     -0:11.6.0 core:backspace (atom-text-editor.editor.power-mode.is-focused)
     -0:10.3.0 editor:select-to-end-of-line (atom-text-editor.editor.power-mode.is-focused.autocomplete-active)
     -0:10.2.0 core:move-right (atom-text-editor.editor.power-mode.is-focused)
     -0:09.8.0 core:save (atom-text-editor.editor.power-mode.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      ".bin",
      "coverage-gutter",
      "git-time-machine",
      "terminal-plus"
    ],
    "ignoredNames": [
      ".git",
      ".DS_Store"
    ],
    "packagesWithKeymapsDisabled": [
      "git-time-machine"
    ]
  },
  "platformio-ide-terminal": {
    "style": {
      "fontSize": "12"
    }
  }
}
```
### Installed Packages

``` coffee
# User
activate-power-mode, v0.5.2
api-docs, v0.0.4
atom-beautify, v0.29.7
atom-ternjs, v0.14.1
atom-typescript, v8.9.1
file-icons, v1.7.11
git-diff-details, v1.3.0
highlight-selected, v0.11.2
imdone-atom, v1.3.29
linter, v1.11.4
linter-json-lint, v0.1.1
php-twig, v4.0.0
platformio-ide-terminal, v2.0.9
pretty-json, v1.0.3
project-switcher2, v1.3.1
react, v0.15.0

# Dev
No dev packages
```
##

**Comment by the-j0k3r** [comment]
try again with 2.9.0
