### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by tdsnoke** [platformio/platformio-atom-ide-terminal#268]
[Enter steps to reproduce:]

1. Launch Atom as a local admin
2. Install platform-ide-terminal package
3. select plus from within atom to create a terminal window in atom 

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [platformio-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) package 2.5.1

### Stack Trace

Uncaught TypeError: Path must be a string. Received undefined

```
At path.js:7

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:184:7)
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.forkPtyProcess (/packages/platformio-ide-terminal/lib/view.coffee:110:25)
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.displayTerminal (/packages/platformio-ide-terminal/lib/view.coffee:119:20)
    at /packages/platformio-ide-terminal/lib/view.coffee:224:10
    at /packages/platformio-ide-terminal/lib/view.coffee:516:7)
    at HTMLDivElement.fn (/packages/platformio-ide-terminal/node_modules/jquery/dist/jquery.js:4855:19)
    at HTMLDivElement.dispatch (/packages/platformio-ide-terminal/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/platformio-ide-terminal/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -1:31.2.0 settings-view:open (atom-pane.pane.active)
     -1:11.3.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
platformio-ide-terminal 2.5.1 
```

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js
