### ISSUE TITLE
error in atom when press + for terminal

### ISSUE THREAD

**Issue by 0mp3s** [platformio/platformio-atom-ide-terminal#280]
<youtube link>
https://youtu.be/Yzmv3aRVNyM
</youtube link>

Error: channel closed
    at ChildProcess.target.send (internal/child_process.js:540:16)
    at Task.module.exports.Task.send (C:\Users\Omerp\AppData\Local\atom\app-1.18.0\resources\app\src\task.js:119:33)
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.input (file:///C:/Users/Omerp/.atom/packages/platformio-ide-terminal/lib/view.coffee:264:17)
    at Terminal.<anonymous> (file:///C:/Users/Omerp/.atom/packages/platformio-ide-terminal/lib/view.coffee:142:8)
    at Terminal.EventEmitter.emit (C:\Users\Omerp\.atom\packages\platformio-ide-terminal\node_modules\term.js\src\term.js:109:12)
    at Terminal.handler (C:\Users\Omerp\.atom\packages\platformio-ide-terminal\node_modules\term.js\src\term.js:3493:8)
    at C:\Users\Omerp\.atom\packages\platformio-ide-terminal\node_modules\term.js\src\term.js:3253:12

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js
