### ISSUE TITLE
Cannot write anything in the terminal.

### ISSUE THREAD

**Issue by niichie** [platformio/platformio-atom-ide-terminal#283]
This was working on the stable release of atom, but after switching over to a fresh install of the latest beta (uninstalled, deleted all leftover folders) I am not able to use the terminal.

When I installed it wouldn't launch at all, and atom asked me to rebuild, so I did and now I can open it but I cant type anything.

This is the error that I am getting in the developer console.
![error](https://user-images.githubusercontent.com/16381287/28034036-068646ba-657e-11e7-96b4-a15ec2238cc6.JPG)

**Comment by tuucan** [comment]
Went through almost the same process, but my install was on top of stable version. Same result.

**Comment by EricHallahan** [comment]
Same here. This is definitely not an isolated problem. I bet it's Atom's rebuild job to blame.

Here is the same log related to the issue, nicely formatted in Markdown:

      Cannot find module '..\build\Release\pty.node'
    (anonymous)                                             @ <embedded>:70936
    (anonymous)                                             @ <embedded>:71013
    module.exports.Emitter.simpleDispatch                   @ <embedded>:63243
    module.exports.Emitter.emit                             @ <embedded>:63359
    (anonymous)                                             @ <embedded>:70965
    emitTwo                                                 @ events.js:106
    emit                                                    @ events.js:191
    process.nextTick                                        @ internal/child_process.js:752
    combinedTickCallback                                    @ internal/process/next_tick.js:67
    _tickCallback                                           @ internal/process/next_tick.js:98
---
      Cannot find module '..\bin\win32\x64.m53.node' Error: Cannot find module '..\bin\win32\x64.m53.node'
        at Function.Module._resolveFilename (module.js:470:15)
        at Function.Module._load (module.js:418:25)
        at Module.require (module.js:498:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (C:\Users\Eric\.atom\packages\platformio-ide-terminal\node_modules\pty.js\lib\pty.js:18:9)
        at Object.<anonymous> (C:\Users\Eric\.atom\packages\platformio-ide-terminal\node_modules\pty.js\lib\pty.js:479:3)
        at Module._compile (module.js:571:32)
        at Object.value [as .js] (C:\ProgramData\Eric\atom\app-1.19.0-beta3\resources\app\src\compile-cache.js:234:23)
        at Module.load (module.js:488:32)
        at tryModuleLoad (module.js:447:12)
        at Function.Module._load (module.js:439:3)
        at Module.require (module.js:498:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (C:\Users\Eric\.atom\packages\platformio-ide-terminal\node_modules\pty.js\lib\pty_win.js:10:20)
        at Object.<anonymous> (C:\Users\Eric\.atom\packages\platformio-ide-terminal\node_modules\pty.js\lib\pty_win.js:418:3)
        at Module._compile (module.js:571:32)
        at Object.value [as .js] (C:\ProgramData\Eric\atom\app-1.19.0-beta3\resources\app\src\compile-cache.js:234:23)
        at Module.load (module.js:488:32)
        at tryModuleLoad (module.js:447:12)
        at Function.Module._load (module.js:439:3)
        at Module.require (module.js:498:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (C:\Users\Eric\.atom\packages\platformio-ide-terminal\node_modules\pty.js\index.js:2:18)
        at Object.<anonymous> (C:\Users\Eric\.atom\packages\platformio-ide-terminal\node_modules\pty.js\index.js:4:3)
        at Module._compile (module.js:571:32)
        at Object.value [as .js] (C:\ProgramData\Eric\atom\app-1.19.0-beta3\resources\app\src\compile-cache.js:234:23)
        at Module.load (module.js:488:32)
        at tryModuleLoad (module.js:447:12)
        at Function.Module._load (module.js:439:3)
        at Module.require (module.js:498:17)
    (anonymous)                                             @ <embedded>:70936
    (anonymous)                                             @ <embedded>:71013
    module.exports.Emitter.simpleDispatch                   @ <embedded>:63243
    module.exports.Emitter.emit                             @ <embedded>:63359
    (anonymous)                                             @ <embedded>:70965
    emitTwo                                                 @ events.js:106
    emit                                                    @ events.js:191
    process.nextTick                                        @ internal/child_process.js:752
    combinedTickCallback                                    @ internal/process/next_tick.js:67
    _tickCallback                                           @ internal/process/next_tick.js:98
---
      handler is not defined ReferenceError: handler is not defined
        at process.<anonymous> (C:\ProgramData\Eric\atom\app-1.19.0-beta3\resources\app\src\task-bootstrap.js:51:20)
        at emitTwo (events.js:106:13)
        at process.emit (events.js:191:7)
        at process.nextTick (internal/child_process.js:752:12)
        at _combinedTickCallback (internal/process/next_tick.js:67:7)
        at process._tickCallback (internal/process/next_tick.js:98:9)
    (anonymous)                                             @ <embedded>:70936
    (anonymous)                                             @ <embedded>:71013
    module.exports.Emitter.simpleDispatch                   @ <embedded>:63243
    module.exports.Emitter.emit                             @ <embedded>:63359
    (anonymous)                                             @ <embedded>:70965
    emitTwo                                                 @ events.js:106
    emit                                                    @ events.js:191
    process.nextTick                                        @ internal/child_process.js:752
    combinedTickCallback                                    @ internal/process/next_tick.js:67
    _tickCallback                                           @ internal/process/next_tick.js:98

**Comment by MikiGrit** [comment]
Same here. Atom 1.19.0-beta7
