### ISSUE TITLE
C++ error

### ISSUE THREAD

**Issue by fliprutledge** [platformio/platformio-atom-ide-terminal#285]
Error: channel closed
    at ChildProcess.target.send (internal/child_process.js:540:16)
    at Task.module.exports.Task.send (C:\Users\Flip\AppData\Local\atom\app-1.18.0\resources\app\src\task.js:119:33)
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.input (file:///C:/Users/Flip/.atom/packages/platformio-ide-terminal/lib/view.coffee:264:17)
    at Terminal.<anonymous> (file:///C:/Users/Flip/.atom/packages/platformio-ide-terminal/lib/view.coffee:142:8)
    at Terminal.EventEmitter.emit (C:\Users\Flip\.atom\packages\platformio-ide-terminal\node_modules\term.js\src\term.js:109:12)
    at Terminal.handler (C:\Users\Flip\.atom\packages\platformio-ide-terminal\node_modules\term.js\src\term.js:3493:8)
    at Terminal.keyDown (C:\Users\Flip\.atom\packages\platformio-ide-terminal\node_modules\term.js\src\term.js:3196:8)
    at HTMLDocument.<anonymous> (C:\Users\Flip\.atom\packages\platformio-ide-terminal\node_modules\term.js\src\term.js:594:29)

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js
