### ISSUE TITLE
this  package could not be loaded

### ISSUE THREAD

**Issue by weiwei02** [platformio/platformio-atom-ide-terminal#337]
There is a bug that describes the message :"`Some installed packages could not be loaded because they contain native modules that were compiled for an earlier version of Atom.`"  When I open Atom, and the details of the bug are as follows :
```
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.9.5 | win32 | x64
gyp http GET https://atom.io/download/electron/v1.6.9/iojs-v1.6.9.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! install error 
gyp ERR! stack Error: connect ETIMEDOUT 52.216.227.16:443
gyp ERR! stack     at Object.exports._errnoException (util.js:1022:11)
gyp ERR! stack     at exports._exceptionWithHostPort (util.js:1045:20)
gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Users\\weiwei\\AppData\\Local\\atom\\app-1.19.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\weiwei\\AppData\\Local\\atom\\app-1.19.0\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "install" "--runtime=electron" "--target=1.6.9" "--dist-url=https://atom.io/download/electron" "--arch=x64" "--ensure"
gyp ERR! cwd C:\Users\weiwei\.atom
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

```

**Comment by ivankravets** [comment]
https://github.com/platformio/platformio-atom-ide-terminal/issues/297
