### ISSUE TITLE
Uncaught TypeError: Cannot read property 'onDidChangeActivePane' of null

### ISSUE THREAD

**Issue by Mr-Thunder** [platformio/platformio-atom-ide-terminal#349]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.3 ia32
**Electron**: 1.6.9
**OS**: Microsoft Windows 7 Enterprise 
**Thrown From**: [platformio-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) package 2.5.5

### Stack Trace

Uncaught TypeError: Cannot read property 'onDidChangeActivePane' of null

```
At C:\Users\ruairi.thunder\AppData\Local\atom\app-1.19.3\resources\app\src\pane.js:221

TypeError: Cannot read property 'onDidChangeActivePane' of null
    at Pane.module.exports.Pane.onDidChangeActive (~/AppData/Local/atom/app-1.19.3/resources/app/src/pane.js:221:34)
    at Pane.module.exports.Pane.observeActive (~/AppData/Local/atom/app-1.19.3/resources/app/src/pane.js:230:25)
    at HTMLElement.PaneElement.initialize (~/AppData/Local/atom/app-1.19.0/resources/app/src/pane-element.js:102:41)
    at Pane.module.exports.Pane.getElement (~/AppData/Local/atom/app-1.19.3/resources/app/src/pane.js:107:99)
    at ViewRegistry.module.exports.ViewRegistry.createView (~/AppData/Local/atom/app-1.19.3/resources/app/src/view-registry.js:87:32)
    at ViewRegistry.module.exports.ViewRegistry.getView (~/AppData/Local/atom/app-1.19.3/resources/app/src/view-registry.js:75:27)
    at /packages/platformio-ide-terminal/lib/status-bar.coffee:139:34
    at PaneContainer.observePanes (~/AppData/Local/atom/app-1.19.3/resources/app/src/pane-container.js:77:47)
    at WorkspaceCenter.observePanes (~/AppData/Local/atom/app-1.19.3/resources/app/src/workspace-center.js:162:37)
    at ~/AppData/Local/atom/app-1.19.3/resources/app/src/workspace.js:900:32
    at Array.map (native)
    at Workspace.observePanes (~/AppData/Local/atom/app-1.19.3/resources/app/src/workspace.js:899:116)
    at StatusBar.module.exports.StatusBar.registerPaneSubscription (/packages/platformio-ide-terminal/lib/status-bar.coffee:138:59)
    at StatusBar.module.exports.StatusBar.createEmptyTerminalView (/packages/platformio-ide-terminal/lib/status-bar.coffee:155:6)
    at StatusBar.module.exports.StatusBar.createTerminalView (/packages/platformio-ide-terminal/lib/status-bar.coffee:152:6)
    at StatusBar.module.exports.StatusBar.newTerminalView (/packages/platformio-ide-terminal/lib/status-bar.coffee:283:24)
    at /packages/atom-typescript/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLElement.dispatch (/packages/atom-typescript/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLElement.elemData.handle (/packages/atom-typescript/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -9:23.1.0 tabs:split-left (div.title.icon.ts-icon.medium-blue.status-modified)
 30x -9:05.1.0 intentions:highlight (input.hidden-input)
     -9:03.7.0 editor:toggle-line-comments (input.hidden-input)
     -8:35.3.0 core:backspace (input.hidden-input)
  8x -7:37.6.0 intentions:highlight (input.hidden-input)
 20x -7:36.9.0 find-and-replace:select-next (input.hidden-input)
     -6:44.1.0 intentions:highlight (input.hidden-input)
     -6:43.9.0 editor:toggle-line-comments (input.hidden-input)
  9x -4:46.9.0 core:move-right (input.hidden-input)
     -4:41.3.0 intentions:highlight (input.hidden-input)
     -4:40.8.0 core:save (input.hidden-input)
  7x -4:31.4.0 core:move-right (input.hidden-input)
     -4:26.1.0 intentions:highlight (input.hidden-input)
     -4:25.6.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
angularjs 0.4.0 
ariake-dark-syntax 0.1.3 
atom-beautify 0.30.5 
atom-bootstrap3 1.2.12 
atom-jshint 2.0.0 
atom-material-ui 2.0.4 
atom-typescript 11.0.7 
auto-detect-indentation 1.3.0 
autoclose-html 0.23.0 
base16-ocean-dark-spacegray 0.13.0 
busy-signal 1.4.3 
color-picker 2.2.5 
css-declaration-sorter 1.1.0 
emmet 2.4.3 
expose 0.14.0 
file-icons 2.1.11 
fonts 3.0.2 
glowing-cursor 0.1.2 
highlight-line 0.12.0 
highlight-selected 0.13.1 
intentions 1.1.5 
language-postcss 1.3.1 
language-pug 0.0.21 
linter 2.2.0 
linter-htmlhint 1.3.3 
linter-jshint 3.1.5 
linter-pug 1.3.1 
linter-sass-lint 1.7.4 
linter-tidy 2.3.1 
linter-ui-default 1.6.7 
minimap 4.29.6 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
minimap-linter 2.0.2 
open-recent 5.0.0 
pigments 0.40.2 
platformio-ide-terminal 2.5.5 
project-manager 3.3.5 
source-preview-postcss 0.1.4 
sync-settings 0.8.2 
```

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js
