### ISSUE TITLE
Uncaught TypeError: Cannot read property 'css' of undefined

### ISSUE THREAD

**Issue by WHMIIICODE** [platformio/platformio-atom-ide-terminal#351]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.3 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.11.6
**Thrown From**: [platformio-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) package 2.6.0

### Stack Trace

Uncaught TypeError: Cannot read property 'css' of undefined

```
At /Users/WHM3/.atom/packages/platformio-ide-terminal/lib/status-bar.coffee:397

TypeError: Cannot read property 'css' of undefined
    at StatusBar.module.exports.StatusBar.onDropTabBar (/packages/platformio-ide-terminal/lib/status-bar.coffee:397:9)
    at StatusBar.onDropTabBar (/packages/platformio-ide-terminal/lib/status-bar.coffee:1:1)
    at /packages/platformio-ide-terminal/lib/status-bar.coffee:142:37)
    at HTMLUListElement.dispatch (/packages/platformio-ide-terminal/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLUListElement.elemData.handle (/packages/platformio-ide-terminal/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
  2x -6:35 core:confirm (input.hidden-input)
  2x -0:46.8.0 platformio-ide-terminal:paste (textarea.)
```

### Non-Core Packages

```
an-old-hope-syntax 1.0.4 
ask-stack 2.2.0 
atom-beautify 0.30.5 
atom-clock 0.1.13 
atom-gpg 0.4.0 
atom-python-run 0.8.1 
atom-runner 2.7.1 
autocomplete-python 1.10.2 
color-picker 2.2.5 
emmet 2.4.3 
file-icons 2.1.11 
highlight-selected 0.13.1 
Hydrogen 1.20.0 
minimap 4.29.6 
minimap-pigments 0.2.2 
pigments 0.40.2 
platformio-ide-terminal 2.6.0 
python-autopep8 0.1.3 
run 0.0.1 
script 3.15.0 
todo 0.6.0 
wakatime 7.0.3 
```

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js
