### ISSUE TITLE
Uncaught TypeError: Cannot read property 'childProcess' of undefined

### ISSUE THREAD

**Issue by tretap** [platformio/platformio-atom-ide-terminal#383]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.0 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [platformio-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) package 2.7.0

### Stack Trace

Uncaught TypeError: Cannot read property 'childProcess' of undefined

```
At C:\Users\ASUS\.atom\packages\platformio-ide-terminal\lib\view.coffee:268

TypeError: Cannot read property 'childProcess' of undefined
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.input (/packages/platformio-ide-terminal/lib/view.coffee:268:19)
    at InputDialog.module.exports.InputDialog.onConfirm (/packages/platformio-ide-terminal/lib/input-dialog.coffee:19:19)
    at /packages/platformio-ide-terminal/lib/dialog.coffee:15:27)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.21.0/resources/app/src/command-registry.js:381:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.21.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.21.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.21.0/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.21.0/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -2:13.2.0 core:move-left (input.hidden-input)
  2x -2:12.7.0 core:backspace (input.hidden-input)
     -2:07.7.0 core:move-down (input.hidden-input)
     -2:07.0 core:move-right (input.hidden-input)
  3x -2:05.8.0 core:backspace (input.hidden-input)
     -1:51.6.0 autocomplete-plus:confirm (input.hidden-input)
  6x -1:51.1.0 core:move-down (input.hidden-input)
     -1:30.5.0 platformio-ide:target:build (input.hidden-input)
     -1:30.5.0 platformio-ide:target:build-C:\Users\ASUS\Documents\PlatformIO\Projects\171007-183630-nucleo_f411re (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:17.7.0 platformio-ide:target:upload (input.hidden-input)
     -1:17.7.0 platformio-ide:target:upload-C:\Users\ASUS\Documents\PlatformIO\Projects\171007-183630-nucleo_f411re (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:41 editor:consolidate-selections (input.hidden-input)
     -0:41 core:cancel (input.hidden-input)
     -0:35.8.0 core:confirm (input.hidden-input)
     -0:31.9.0 editor:consolidate-selections (input.hidden-input)
     -0:31.9.0 core:cancel (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-clang 0.11.3 
build 0.69.0 
busy-signal 1.4.3 
file-icons 2.1.12 
intentions 1.1.5 
language-ini 1.19.0 
linter 2.2.0 
linter-gcc 0.7.1 
linter-ui-default 1.6.10 
platformio-ide 2.0.0-rc.3 
platformio-ide-debugger 1.2.4 
platformio-ide-terminal 2.7.0 
tool-bar 1.1.0 
```

**Comment by the-j0k3r** [comment]
retest with 2.9.0
