### ISSUE TITLE
Uncaught Error: Cannot find module '../src/term' #245

### ISSUE THREAD

**Issue by webstuff56** [platformio/platformio-atom-ide-terminal#389]

**Comment by itsaandy** [comment]
Having the same problem.

**Comment by tpradeep8** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.27.2 x64
**Electron**: 1.7.15
**OS**: Microsoft Windows 10 Home
**Thrown From**: [platformio-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) package 2.8.1


### Stack Trace

Uncaught Error: Cannot find module '../src/term'

```
At module.js:472

Error: Cannot find module '../src/term'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.27.2/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.27.2/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.27.2/resources/app/src/native-compile-cache.js:66:33)
    at Function.Terminal (/packages/platformio-ide-terminal/node_modules/term.js/lib/index.js:48:27)
    at Function.module.exports.PlatformIOTerminalView.getFocusedTerminal (/packages/platformio-ide-terminal/lib/view.coffee:40:20)
    at /packages/platformio-ide-terminal/lib/status-bar.coffee:98:44
```

### Commands

```
  2x -2:55.1.0 settings-view:open (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:37.2.0 tabs:close-all-tabs (div.title)
```

### Non-Core Packages

```
platformio-ide-terminal 2.8.1 
```

**Comment by bostone** [comment]
Still here on Aug 17, 2018 with v. 1.29.0

**Comment by the-j0k3r** [comment]
@bostone Im looking tried to duplicate and cant.

```
C:\Users\Joker> atom -v

Atom    : 1.29.0
Electron: 2.0.5
Chrome  : 61.0.3163.100
Node    : 8.9.3
C:\Users\Joker> apm -v

apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.29.0
python 3.5.2
git 2.18.0.windows.1
visual studio
```

Windows 10 pro 1803 and 1709 64bit
Platformio-ide-terminal: 2.8.4

Maybe you would consider the issue to be local to you or your setup.

Try the following https://flight-manual.atom.io/hacking-atom/sections/debugging/#reset-to-factory-defaults

Then if you have non-core extensions install one, text, install another test, until issue repeats just in case theres something affecting the terminal.

Ive been wondering a few other issues I cant duplicate all seem to come from Windows 10 home, Im sure thats only a coincidence, but IDK..

**Comment by the-j0k3r** [comment]
All errors indicate Atom failure not Platformio-ide-terminal.
