### ISSUE TITLE
Uncaught TypeError: Cannot read property 'runCommandInNewTerminal' of undefined

### ISSUE THREAD

**Issue by BernardDoherty** [platformio/platformio-atom-ide-terminal#398]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.4
**Thrown From**: [platformio-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) package 2.7.0

### Stack Trace

Uncaught TypeError: Cannot read property 'runCommandInNewTerminal' of undefined

```
At /Users/bernarddoherty/.atom/packages/platformio-ide-terminal/lib/platformio-ide-terminal.coffee:23

TypeError: Cannot read property 'runCommandInNewTerminal' of undefined
    at Object.run (/packages/platformio-ide-terminal/lib/platformio-ide-terminal.coffee:23:21)
    at TestRunner.module.exports.TestRunner.run (/packages/ruby-test/lib/test-runner.coffee:27:17)
    at RubyTestView.module.exports.RubyTestView.runTest (/packages/ruby-test/lib/ruby-test-view.coffee:57:13)
    at RubyTestView.module.exports.RubyTestView.testFile (/packages/ruby-test/lib/ruby-test-view.coffee:41:6)
    at /packages/ruby-test/lib/ruby-test-view.coffee:16:68)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:381:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -1:32.3.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling)
     -0:39.2.0 core:close (div.panels-item)
     -0:36.3.0 tree-view:toggle (input.hidden-input)
  2x -0:32.7.0 ruby-test:test-file (input.hidden-input)
```

### Non-Core Packages

```
an-old-hope-light-syntax 1.0.1 
an-old-hope-syntax 1.0.4 
atom-beautify 0.30.6 
atom-espresso-soda-theme 0.10.1 
atom-handlebars 1.3.0 
atom-hg 2.0.14 
atom-ide-ui 0.5.3 
atom-material-syntax 1.0.7 
atom-material-syntax-light 0.4.6 
atom-material-ui 2.0.6 
atom-monokai 0.10.4 
atom-ternjs 0.18.3 
ayu 0.1.0 
busy-signal 1.4.3 
custom-title 1.0.1 
duotone-denim-syntax 0.4.3 
duotone-light-cave-syntax 0.1.3 
duotone-light-syntax 2.1.0 
duotone-snow 2.0.2 
duotone-stark-sea-syntax 2.1.0-3 
ember-snippets 2.1.3 
ember-tabs 2.4.3 
emmet 2.4.3 
file-icons 2.1.12 
flatwhite-syntax 0.8.1 
foldername-tabs 0.2.4 
gl-light-syntax 2.2.0 
highlight-selected 0.13.1 
intentions 1.1.5 
isotope-light-ui 2.2.7 
isotope-ui 2.7.1 
language-babel 2.76.3 
language-ember-htmlbars 0.4.0 
linter 2.2.0 
linter-eslint 8.4.0 
linter-ruby 1.2.6 
linter-ui-default 1.6.10 
local-history 4.3.1 
material-design-syntax 1.8.0 
monokai 0.18.0 
monokai-dark 1.3.0 
monokai-seti 0.7.0 
native-ui 0.18.2 
nucleus-dark-ui 0.9.0 
pen-paper-coffee-syntax 0.14.9 
pigments 0.40.2 
platformio-ide-terminal 2.7.0 
rails-snippets 2.16.0 
react-es6-snippets 0.3.0 
react-snippets 1.0.0 
ruby-block 0.3.6 
ruby-test 1.0.2 
ruby-test-switcher 1.2.3 
save-workspace 0.4.0 
seti-syntax 1.0.1 
seti-ui 1.3.1 
spacegray-dark-ui 0.12.0 
split-diff 1.5.1 
sync-settings 0.8.3 
tabs-to-spaces 1.0.3 
unity-ui 2.1.5 
yeti-syntax 0.1.2 
yeti-ui 0.1.6 
```

**Comment by the-j0k3r** [comment]
Please retest with platformio-ide-terminal 2.9.0
