### ISSUE TITLE
Uncaught TypeError: atom.workspace.getCenter is not a function

### ISSUE THREAD

**Issue by vkkevin** [platformio/platformio-atom-ide-terminal#399]
**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Ubuntu 14.04.5
**Thrown From**: [platformio-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) package 2.7.0

### Stack Trace

Uncaught TypeError: atom.workspace.getCenter is not a function

```
At /home/xxx/.atom/packages/platformio-ide-terminal/lib/view.coffee:188

TypeError: atom.workspace.getCenter is not a function
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.maximize (/packages/platformio-ide-terminal/lib/view.coffee:188:47)
    at /packages/platformio-ide-terminal/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLButtonElement.dispatch (/packages/platformio-ide-terminal/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/packages/platformio-ide-terminal/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -2:15.1.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-clock 0.1.15 
autocomplete-paths 2.12.1 
busy-signal 1.4.3 
file-icons 2.1.7 
gcc-make-run 0.2.12 
highlight-selected 0.13.1 
intentions 1.1.5 
language-x86asm 0.9.0 
linter 2.2.0 
linter-csslint 2.0.0 
linter-gcc 0.7.1 
linter-htmlhint 1.4.0 
linter-php 1.5.1 
linter-ui-default 1.2.4 
minimap 4.29.7 
minimap-highlight-selected 4.6.1 
minimap-linter 2.1.3 
platformio-ide-terminal 2.7.0 
simplified-chinese-menu 5.3.4 
```

**Comment by takumiabe** [comment]
getCenter introduced at Atom v1.17.0, so It will fix when updating atom.
