### ISSUE TITLE
Failed to activate the platformio-ide-terminal package (ATOM BETA 1.23)

### ISSUE THREAD

**Issue by conradolucas** [platformio/platformio-atom-ide-terminal#403]
target[Symbol.iterator] is not a function
Hide Stack Trace
TypeError: target[Symbol.iterator] is not a function
    at TooltipManager.add (/usr/share/atom-beta/resources/app/src/tooltip-manager.js:117:35)
    at StatusBar.module.exports.StatusBar.initialize (/home/conradolucas/.atom/packages/platformio-ide-terminal/lib/status-bar.coffee:84:38)
    at StatusBar.View [as constructor] (/home/conradolucas/.atom/packages/pdf-view/node_modules/space-pen/lib/space-pen.js:184:25)
    at new StatusBar (/home/conradolucas/.atom/packages/platformio-ide-terminal/lib/status-bar.coffee:12:7)
    at Object.consumeStatusBar (/home/conradolucas/.atom/packages/platformio-ide-terminal/lib/platformio-ide-terminal.coffee:28:26)
    at Provider.module.exports.Provider.provide (/usr/share/atom-beta/resources/app/node_modules/service-hub/lib/provider.js:34:58)
    at ServiceHub.module.exports.ServiceHub.consume (/usr/share/atom-beta/resources/app/node_modules/service-hub/lib/service-hub.js:50:24)
    at Package.module.exports.Package.activateServices (/usr/share/atom-beta/resources/app/src/package.js:456:81)
    at Package.module.exports.Package.activateNow (/usr/share/atom-beta/resources/app/src/package.js:258:22)
    at /usr/share/atom-beta/resources/app/src/package.js:1068:34
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom-beta/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom-beta/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at triggeredActivationHooks.forEach.hook (/usr/share/atom-beta/resources/app/src/package-manager.js:705:86)
    at Set.forEach (native)
    at PackageManager.activatePackage (/usr/share/atom-beta/resources/app/src/package-manager.js:705:43)
    at packagesToEnable.forEach.name (/usr/share/atom-beta/resources/app/src/package-manager.js:440:51)
    at Array.forEach (native)
    at disabledPackagesSubscription.config.onDidChange (/usr/share/atom-beta/resources/app/src/package-manager.js:440:30)
    at /usr/share/atom-beta/resources/app/src/config.js:693:26
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom-beta/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom-beta/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Config.module.exports.Config.emitChangeEvent (/usr/share/atom-beta/resources/app/src/config.js:884:35)
    at Config.module.exports.Config.setRawValue (/usr/share/atom-beta/resources/app/src/config.js:670:25)
    at Config.module.exports.Config.set (/usr/share/atom-beta/resources/app/src/config.js:248:20)
    at Config.module.exports.Config.removeAtKeyPath (/usr/share/atom-beta/resources/app/src/config.js:407:18)
    at Package.module.exports.Package.enable (/usr/share/atom-beta/resources/app/src/package.js:84:32)
    at PackageManager.enablePackage (/usr/share/atom-beta/resources/app/src/package-manager.js:246:18)
    at HTMLButtonElement.enablementButtonClickHandler (/usr/share/atom-beta/resources/app/node_modules/settings-view/lib/package-card.js:361:31)
The error was thrown from the platformio-ide-terminal package. This issue has already been reported.

**HELP-ME**

**Comment by ghost** [comment]
Same probleme here !
:-/

**Comment by chenjau** [comment]
seems atom commit:[6e55b29](https://github.com/atom/atom/commit/6e55b293312ab57f647d05e7584cb05c67436666) break it.  
previous commit d715f3ee2 working fine.

**Comment by UziTech** [comment]
This seems to be an issue with Atom 1.23.0 adding tooltips to an element from `atom-space-pen-view`

**Comment by UziTech** [comment]
same issue https://github.com/morassman/process-palette/issues/55

**Comment by UziTech** [comment]
this is fixed in https://github.com/atom/atom/pull/16144
