### ISSUE TITLE
Failed to activate the platformio-ide-terminal package

### ISSUE THREAD

**Issue by mirelopxaneb** [platformio/platformio-atom-ide-terminal#406]
target[Symbol.iterator] is not a function

TypeError: target[Symbol.iterator] is not a function
    at TooltipManager.add (/Applications/Atom Beta.app/Contents/Resources/app/src/tooltip-manager.js:117:35)
    at StatusBar.module.exports.StatusBar.initialize (/Users/mirelopxaneb/.atom/packages/platformio-ide-terminal/lib/status-bar.coffee:84:38)
    at StatusBar.View [as constructor] (/Users/mirelopxaneb/.atom/packages/script/node_modules/space-pen/lib/space-pen.js:184:25)
    at new StatusBar (/Users/mirelopxaneb/.atom/packages/platformio-ide-terminal/lib/status-bar.coffee:12:7)
    at Object.consumeStatusBar (/Users/mirelopxaneb/.atom/packages/platformio-ide-terminal/lib/platformio-ide-terminal.coffee:28:26)
    at Provider.module.exports.Provider.provide (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/service-hub/lib/provider.js:34:58)
    at ServiceHub.module.exports.ServiceHub.consume (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/service-hub/lib/service-hub.js:50:24)
    at Package.module.exports.Package.activateServices (/Applications/Atom Beta.app/Contents/Resources/app/src/package.js:456:81)
    at Package.module.exports.Package.activateNow (/Applications/Atom Beta.app/Contents/Resources/app/src/package.js:258:22)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/package.js:1068:34
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at triggeredActivationHooks.forEach.hook (/Applications/Atom Beta.app/Contents/Resources/app/src/package-manager.js:705:86)
    at Set.forEach (native)
    at PackageManager.activatePackage (/Applications/Atom Beta.app/Contents/Resources/app/src/package-manager.js:705:43)
    at packagesToEnable.forEach.name (/Applications/Atom Beta.app/Contents/Resources/app/src/package-manager.js:440:51)
    at Array.forEach (native)
    at disabledPackagesSubscription.config.onDidChange (/Applications/Atom Beta.app/Contents/Resources/app/src/package-manager.js:440:30)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/config.js:693:26
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Config.module.exports.Config.emitChangeEvent (/Applications/Atom Beta.app/Contents/Resources/app/src/config.js:884:35)
    at Config.module.exports.Config.setRawValue (/Applications/Atom Beta.app/Contents/Resources/app/src/config.js:670:25)
    at Config.module.exports.Config.set (/Applications/Atom Beta.app/Contents/Resources/app/src/config.js:248:20)
    at Config.module.exports.Config.removeAtKeyPath (/Applications/Atom Beta.app/Contents/Resources/app/src/config.js:407:18)
    at Package.module.exports.Package.enable (/Applications/Atom Beta.app/Contents/Resources/app/src/package.js:84:32)
    at PackageManager.enablePackage (/Applications/Atom Beta.app/Contents/Resources/app/src/package-manager.js:246:18)
    at HTMLButtonElement.enablementButtonClickHandler (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/settings-view/lib/package-card.js:361:31)

**Comment by judewang** [comment]
This issue has been opened before and already has a fixed in https://github.com/atom/atom/pull/16144.

#403

**Comment by bonsoirval** [comment]
Steps I used to solve mine:
Download the package from : https://github.com/platformio/platformio-atom-ide-terminal
unzip it and copy the folder into username/.atom/packages
Note:
In my case, the folder was named:
platformio-atom-ide-terminal-master 
What I did
cd username/.atom/packages/platformio-atom-ide-terminal-master
apm install
Note: That was all that solved the problem and my terminal was back

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js
