### ISSUE TITLE
Uncaught Error: EPERM: operation not permitted, open '$ATOM_HOME/packages\platformio-ide-terminal...

### ISSUE THREAD

**Issue by rayneo777** [platformio/platformio-atom-ide-terminal#407]
[Enter steps to reproduce:]

There were no steps executed. The error message just came out suddenly when viewing Python source code already saved.

The screenshot is

[2017-11-13 ATOM UNCAUGHT ERROR WITH SCREENSHOT AND STACK TRACE.docx](https://github.com/platformio/platformio-atom-ide-terminal/files/1465622/2017-11-13.ATOM.UNCAUGHT.ERROR.WITH.SCREENSHOT.AND.STACK.TRACE.docx)

.

**Atom**: 1.22.0 ia32
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Home
**Thrown From**: [platformio-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) package 2.7.0

### Stack Trace

Uncaught Error: EPERM: operation not permitted, open 'C:\Users\Raymond\.atom\packages\platformio-ide-terminal\node_modules\term.js\src\term.js'

```
At fs.js:558

Error: EPERM: operation not permitted, open 'C:\Users\Raymond\.atom\packages\platformio-ide-terminal\node_modules\term.js\src\term.js'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Proxy.fs.readFileSync (fs.js:468:33)
    at Proxy.fs.readFileSync (ELECTRON_ASAR.js:506:29)
    at compileFileAtPath (~/AppData/Local/atom/app-1.22.0/resources/app/src/compile-cache.js:89:29)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.22.0/resources/app/src/compile-cache.js:238:26)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.22.0/resources/app/src/native-compile-cache.js:66:33)
    at Function.Terminal (/packages/platformio-ide-terminal/node_modules/term.js/lib/index.js:48:27)
    at Function.module.exports.PlatformIOTerminalView.getFocusedTerminal (/packages/platformio-ide-terminal/lib/view.coffee:40:20)
    at /packages/platformio-ide-terminal/lib/status-bar.coffee:97:44
```

### Commands

```
     -1:48.5.0 core:backspace (input.hidden-input)
     -1:27.3.0 editor:newline (input.hidden-input)
  8x -1:21.4.0 core:backspace (input.hidden-input)
  2x -0:46 editor:newline (input.hidden-input)
```

### Non-Core Packages

```
platformio-ide-terminal 2.7.0 
```

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0.
These type issues all so far seem fixed with this release due to using node-pty-prebuilt instead unmaintained and outdated pty.js
