### ISSUE TITLE
can not open bash on Win

### ISSUE THREAD

**Issue by sijichun** [platformio/platformio-atom-ide-terminal#412]
I am using this terminal with "bash on ubuntu on windows". Originally, it works well, but after the latest updating, the terminal cannot be opened.
The error info:

`<embedded>:70792 spell-check:en-us Can't load en_US: Cannot find dictionary for en_US.
<embedded>:70795 Cannot find module '..\build\Release\pty.node'
<embedded>:70798 Objectcode: "ENOENT"errno: -4058path: "C:\Users\sijic\.atom\packages\platformio-ide-terminal\node_modules\pty.js\bin\win32\x64_m49\pty.node.bak"syscall: "lstat"__proto__: Object(anonymous function) @ <embedded>:70798
<embedded>:70798 The specified module could not be found.
\\?\C:\Users\sijic\.atom\packages\platformio-ide-terminal\node_modules\pty.js\bin\win32\x64_m49\pty.node Error: The specified module could not be found.
\\?\C:\Users\sijic\.atom\packages\platformio-ide-terminal\node_modules\pty.js\bin\win32\x64_m49\pty.node
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:168:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:168:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\sijic\.atom\packages\platformio-ide-terminal\node_modules\pty.js\lib\pty.js:27:9)
    at Module._compile (module.js:556:32)
    at Object.value [as .js] (C:\Users\sijic\AppData\Local\atom\app-1.18.0\resources\app\src\compile-cache.js:234:23)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\sijic\.atom\packages\platformio-ide-terminal\node_modules\pty.js\lib\pty_win.js:10:36)
    at Module._compile (module.js:556:32)
    at Object.value [as .js] (C:\Users\sijic\AppData\Local\atom\app-1.18.0\resources\app\src\compile-cache.js:234:23)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\sijic\.atom\packages\platformio-ide-terminal\node_modules\pty.js\index.js:2:18)
    at Module._compile (module.js:556:32)
    at Object.value [as .js] (C:\Users\sijic\AppData\Local\atom\app-1.18.0\resources\app\src\compile-cache.js:234:23)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)(anonymous function) @ <embedded>:70798
<embedded>:70798 Cannot read property 'bind' of null TypeError: Cannot read property 'bind' of null
    at process.<anonymous> (C:\Users\sijic\AppData\Local\atom\app-1.18.0\resources\app\src\task-bootstrap.js:82:23)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)(anonymous function) @ <embedded>:70798`

**Comment by sijichun** [comment]
problem solved, thanks.
