### ISSUE TITLE
Unexpected token illegal

### ISSUE THREAD

**Issue by merlinstardust** [platformio/platformio-atom-ide-terminal#430]
I just installed this and upon opening a terminal, I got the below error trace.

I tried

* running both commands it suggested
* restarting Atom

But neither has fixed the problem.

```
/usr/local/lib/node_modules/npm/lib/utils/unsupported.js:27
        console.error(`a bug known to break npm. Please update to at least ${r
                      ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:19:21
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:92:3)
    at Module._compile (module.js:460:26)
nvm is not compatible with the npm config "prefix" option: currently set to ""

Run `npm config delete prefix` or `nvm use --delete-prefix v8.8.1 --silent` to unset it.
```

**Comment by jonny-harte** [comment]
Exact same for me!

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js

if issues persist open a new ticket with required information.

Thx =)
