### ISSUE TITLE
How to fix it

### ISSUE THREAD

**Issue by nitiz143** [platformio/platformio-atom-ide-terminal#440]
[Enter steps to reproduce:]

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: [platformio-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) package 2.7.0

### Stack Trace

Uncaught Error: channel closed

```
At events.js:160

Error: channel closed
    at ChildProcess.target.send (internal/child_process.js:548:16)
    at Task.module.exports.Task.send (~/AppData/Local/atom/app-1.23.1/resources/app/src/task.js:113:33)
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.resize (/packages/platformio-ide-terminal/lib/view.coffee:276:17)
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.resizeTerminalToView (/packages/platformio-ide-terminal/lib/view.coffee:503:6)
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.focus (/packages/platformio-ide-terminal/lib/view.coffee:465:6)
    at PlatformIOTerminalView.focus (/packages/platformio-ide-terminal/lib/view.coffee:1:1)
    at /packages/platformio-ide-terminal/lib/view.coffee:190:26
    at /packages/platformio-ide-terminal/lib/view.coffee:524:7)
    at HTMLDivElement.fn (/packages/platformio-ide-terminal/node_modules/jquery/dist/jquery.js:4855:19)
    at HTMLDivElement.dispatch (/packages/platformio-ide-terminal/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/platformio-ide-terminal/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
```

### Non-Core Packages

```
atom-bootstrap3 1.2.12 
busy-signal 1.4.3 
intentions 1.1.5 
linter 2.2.0 
linter-ui-default 1.6.10 
platformio-ide-terminal 2.7.0 
prettier-atom 0.43.1 
react-snippets 1.0.1 
```

**Comment by the-j0k3r** [comment]
duplicated of #556  @ivankravets please close
