### ISSUE TITLE
Uncaught TypeError: this.terminal.stopScrolling is not a function

### ISSUE THREAD

**Issue by Sunicho** [platformio/platformio-atom-ide-terminal#447]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.2 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: [platformio-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) package 2.8.0

### Stack Trace

Uncaught TypeError: this.terminal.stopScrolling is not a function

```
At C:\Users\Administrator\.atom\packages\platformio-atom-ide-terminal\lib\view.coffee:270

TypeError: this.terminal.stopScrolling is not a function
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.input (/packages/platformio-atom-ide-terminal/lib/view.coffee:270:15)
    at /packages/platformio-atom-ide-terminal/lib/view.coffee:149:8)
    at Terminal.EventEmitter.emit (/packages/node_modules/term.js/src/term.js:109:12)
    at Terminal.handler (/packages/node_modules/term.js/src/term.js:3109:8)
    at Terminal.keyDown (/packages/node_modules/term.js/src/term.js:2829:8)
    at /packages/node_modules/term.js/src/term.js:571:29)
```

### Commands

```
```

### Non-Core Packages

```
atom-space-pen-views 2.2.0 
node_modules undefined 
platformio-ide-terminal 2.8.0 
space-pen 5.1.2 
```

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js
