### ISSUE TITLE
Platformio IDE prompt is not received 

### ISSUE THREAD

**Issue by chander-parwani** [platformio/platformio-atom-ide-terminal#482]
![capture](https://user-images.githubusercontent.com/16186858/37519527-6aaed802-293f-11e8-9f13-1a57328de596.PNG)

**Comment by Razcle** [comment]
I have the same issue

**Comment by digomes87** [comment]
me too, the same wrong

![screen shot 2018-03-16 at 10 17 19 am](https://user-images.githubusercontent.com/5879047/37522646-4b5da438-2903-11e8-9691-32fb2a7def4a.png)

**Comment by finbarmaginn** [comment]
same here

**Comment by ritou11** [comment]
+1 same here

**Comment by ritou11** [comment]
Cannot find module '../build/Release/pty.node'
(anonymous) @ <embedded>:75428
(anonymous) @ <embedded>:75505
module.exports.Emitter.simpleDispatch @ <embedded>:66262
module.exports.Emitter.emit @ <embedded>:66378
(anonymous) @ <embedded>:75457
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
events.js:106 Object {errno: -2, code: "ENOENT", syscall: "lstat", path: "/Users/haotian/.atom/packages/platformio-ide-termi…de_modules/pty.js/bin/darwin/x64_m54/pty.node.bak"}code: "ENOENT"errno: -2path: "/Users/haotian/.atom/packages/platformio-ide-terminal/node_modules/pty.js/bin/darwin/x64_m54/pty.node.bak"syscall: "lstat"__proto__: Object
(anonymous) @ <embedded>:75431
(anonymous) @ <embedded>:75505
module.exports.Emitter.simpleDispatch @ <embedded>:66262
module.exports.Emitter.emit @ <embedded>:66378
(anonymous) @ <embedded>:75457
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
events.js:106 Cannot find module '/Users/haotian/.atom/packages/platformio-ide-terminal/node_modules/pty.js/bin/darwin/x64_m54/pty.node' Error: Cannot find module '/Users/haotian/.atom/packages/platformio-ide-terminal/node_modules/pty.js/bin/darwin/x64_m54/pty.node'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/haotian/.atom/packages/platformio-ide-terminal/node_modules/pty.js/lib/pty.js:27:9)
    at Object.<anonymous> (/Users/haotian/.atom/packages/platformio-ide-terminal/node_modules/pty.js/lib/pty.js:487:3)
    at Module._compile (module.js:571:32)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:235:23)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/haotian/.atom/packages/platformio-ide-terminal/node_modules/pty.js/index.js:2:18)
    at Object.<anonymous> (/Users/haotian/.atom/packages/platformio-ide-terminal/node_modules/pty.js/index.js:4:3)
    at Module._compile (module.js:571:32)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:235:23)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/haotian/.atom/packages/platformio-ide-terminal/lib/process.coffee:1:7)
    at Object.<anonymous> (/Users/haotian/.atom/packages/platformio-ide-terminal/lib/process.coffee:1:1)
    at Object.<anonymous> (/Users/haotian/.atom/packages/platformio-ide-terminal/lib/process.coffee:1:1)
    at Module._compile (module.js:571:32)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:235:23)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
(anonymous) @ <embedded>:75431
(anonymous) @ <embedded>:75505
module.exports.Emitter.simpleDispatch @ <embedded>:66262
module.exports.Emitter.emit @ <embedded>:66378
(anonymous) @ <embedded>:75457
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
events.js:106 handler is not defined ReferenceError: handler is not defined
    at process.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/task-bootstrap.js:51:20)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:194:7)
    at process.nextTick (internal/child_process.js:766:12)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
(anonymous) @ <embedded>:75431
(anonymous) @ <embedded>:75505
module.exports.Emitter.simpleDispatch @ <embedded>:66262
module.exports.Emitter.emit @ <embedded>:66378
(anonymous) @ <embedded>:75457
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104

**Comment by Kogoruhn** [comment]
+1. HALP

**Comment by roddypratt** [comment]
Duplicate of #477

**Comment by digomes87** [comment]
Here in this link https://github.com/platformio/platformio-atom-ide-terminal/issues/477
this guy says ivankravets  which need wait for new rebuild. 
it looks like it has to compile for each version of O.S

**Comment by Kogoruhn** [comment]
Guys, take this https://github.com/atom/atom/tree/v1.24.1

Until  [this](https://github.com/platformio/platformio-atom-ide-terminal/issues/477#issuecomment-373662082)

**Comment by kushalj001** [comment]
+1

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-atom-ide-terminal/issues/477
