### ISSUE TITLE
Cannot read property 'split' of undefined - Atom

### ISSUE THREAD

**Issue by kaustubhhiware** [platformio/platformio-atom-ide-terminal#487]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.1 x64
**Electron**: 1.6.16
**OS**: Ubuntu 16.04.4
**Thrown From**: [platformio-atom-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) package 2.8.1

### Stack Trace

Uncaught TypeError: Cannot read property 'split' of undefined

```
At /home/kaustubh/.atom/packages/platformio-atom-ide-terminal/lib/status-bar.coffee:153

TypeError: Cannot read property 'split' of undefined
    at StatusBar.module.exports.StatusBar.createTerminalView (/packages/platformio-atom-ide-terminal/lib/status-bar.coffee:153:26)
    at StatusBar.module.exports.StatusBar.newTerminalView (/packages/platformio-atom-ide-terminal/lib/status-bar.coffee:293:24)
    at /packages/atom-pdf-view/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLElement.dispatch (/packages/atom-pdf-view/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLElement.elemData.handle (/packages/atom-pdf-view/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
```

### Non-Core Packages

```
file-icons 2.1.3 
atom-ide-ui 0.3.2 
atom-material-syntax 1.0.6 
atom-material-ui 2.0.4 
Atom-MD-Icon undefined 
pdf-view 0.57.0 
pigments 0.40.2 
autocomplete-emojis 2.5.0 
git-time-machine 1.5.9 
minimap 4.27.1 
platformio-ide-terminal 2.8.1 
```

**Comment by abelit** [comment]
i come across this probelm again on my macOSX 10.13，please help solving it.

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0.
These type issues all so far seem fixed with this release due to using node-pty-prebuilt instead unmaintained and outdated pty.js
