### ISSUE TITLE
Terminal hangs

### ISSUE THREAD

**Issue by slacaze** [platformio/platformio-atom-ide-terminal#496]
Iknow it's been reported in other issues, I just though I would add the output of my Developer Tools Console:

events.js:106 Cannot find module '..\build\Release\pty.node'
(anonymous) @ <embedded>:75428
(anonymous) @ <embedded>:75505
module.exports.Emitter.simpleDispatch @ <embedded>:66262
module.exports.Emitter.emit @ <embedded>:66378
(anonymous) @ <embedded>:75457
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
events.js:106 Object {errno: -4058, code: "ENOENT", syscall: "lstat", path: "C:\Users\slacaze\.atom\packages\platformio-ide-ter…de_modules\pty.js\bin\win32\ia32_m54\pty.node.bak"}
(anonymous) @ <embedded>:75431
(anonymous) @ <embedded>:75505
module.exports.Emitter.simpleDispatch @ <embedded>:66262
module.exports.Emitter.emit @ <embedded>:66378
(anonymous) @ <embedded>:75457
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
events.js:106 %1 is not a valid Win32 application.
\\?\C:\Users\slacaze\.atom\packages\platformio-ide-terminal\node_modules\pty.js\bin\win32\ia32_m54\pty.node Error: %1 is not a valid Win32 application.
\\?\C:\Users\slacaze\.atom\packages\platformio-ide-terminal\node_modules\pty.js\bin\win32\ia32_m54\pty.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\slacaze\.atom\packages\platformio-ide-terminal\node_modules\pty.js\lib\pty.js:27:9)
    at Object.<anonymous> (C:\Users\slacaze\.atom\packages\platformio-ide-terminal\node_modules\pty.js\lib\pty.js:487:3)
    at Module._compile (module.js:571:32)
    at Object.value [as .js] (C:\Users\slacaze\AppData\Local\atom\app-1.25.0\resources\app.asar\src\compile-cache.js:235:23)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\slacaze\.atom\packages\platformio-ide-terminal\node_modules\pty.js\lib\pty_win.js:10:20)
    at Object.<anonymous> (C:\Users\slacaze\.atom\packages\platformio-ide-terminal\node_modules\pty.js\lib\pty_win.js:410:3)
    at Module._compile (module.js:571:32)
    at Object.value [as .js] (C:\Users\slacaze\AppData\Local\atom\app-1.25.0\resources\app.asar\src\compile-cache.js:235:23)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\slacaze\.atom\packages\platformio-ide-terminal\node_modules\pty.js\index.js:2:18)
    at Object.<anonymous> (C:\Users\slacaze\.atom\packages\platformio-ide-terminal\node_modules\pty.js\index.js:4:3)
    at Module._compile (module.js:571:32)
    at Object.value [as .js] (C:\Users\slacaze\AppData\Local\atom\app-1.25.0\resources\app.asar\src\compile-cache.js:235:23)
(anonymous) @ <embedded>:75431
(anonymous) @ <embedded>:75505
module.exports.Emitter.simpleDispatch @ <embedded>:66262
module.exports.Emitter.emit @ <embedded>:66378
(anonymous) @ <embedded>:75457
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
events.js:106 handler is not defined ReferenceError: handler is not defined
    at process.<anonymous> (C:\Users\slacaze\AppData\Local\atom\app-1.25.0\resources\app.asar\src\task-bootstrap.js:51:20)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:194:7)
    at process.nextTick (internal/child_process.js:766:12)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
(anonymous) @ <embedded>:75431
(anonymous) @ <embedded>:75505
module.exports.Emitter.simpleDispatch @ <embedded>:66262
module.exports.Emitter.emit @ <embedded>:66378
(anonymous) @ <embedded>:75457
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104

**Comment by OsBlaineOra** [comment]
#477 is closed but this is still a problem.

I have re-installed platformio-atom-ide-terminal several times and atom once.

I get pretty much the same error listed above.  If there's any specific troubleshooting I can do to help out, let me know.

**Comment by slacaze** [comment]
I tried updating to Atom 64, and then uninstalled, reinstalled all my packages.

They all work, except for platformio-ide-terminal, which throws:

![2018-04-11 10_31_57-microsoft visual c runtime library](https://user-images.githubusercontent.com/24715934/38608720-091f1ac2-3d74-11e8-8760-8da2165d7060.png)

**Comment by slacaze** [comment]
I tried both recommendation in #246, but none worked.

**Comment by slacaze** [comment]
JavaScript trace in case that is relevant:

![2018-04-11 10_56_26-atom](https://user-images.githubusercontent.com/24715934/38609841-11c08672-3d77-11e8-959f-fddbe674aead.png)

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0.
These type issues all so far seem fixed with this release due to using node-pty-prebuilt instead unmaintained and outdated pty.js
