### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Jeronimus28** [platformio/platformio-atom-ide-terminal#507]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.1 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.4
**Thrown From**: [platformio-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) package 2.8.1

### Stack Trace

Uncaught RangeError: Maximum call stack size exceeded

```
At /Users/j.twigt/.atom/packages/platformio-ide-terminal/node_modules/jquery/dist/jquery.js:800

RangeError: Maximum call stack size exceeded
    at /packages/platformio-ide-terminal/node_modules/jquery/dist/jquery.js:800:10)
    at jQuery.fn.init.find (/packages/platformio-ide-terminal/node_modules/jquery/dist/jquery.js:2695:11)
    at /packages/quick-query/lib/quick-query-result-view.coffee:153:18)
```

### Commands

```
  2x -7:20.9.0 core:backspace (input.hidden-input)
     -7:20.4.0 quick-query:run (input.hidden-input)
     -0:16.8.0 core:select-all (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 1.4.3 
data-atom 0.29.0 
Hydrogen 2.3.0 
intentions 1.1.5 
language-pgsql 0.2.3 
linter 2.2.0 
linter-spell 0.15.0 
linter-ui-default 1.7.1 
markdown-preview-plus 2.5.7 
pg-formatter 0.0.1 
platformio-ide-terminal 2.8.1 
quick-query 0.12.4 
tool-bar 1.1.7 
```

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0.
These type issues all so far seem fixed with this release due to using node-pty-prebuilt instead unmaintained and outdated pty.js
