### ISSUE TITLE
Uncaught TypeError: InputDialog is not a constructor

### ISSUE THREAD

**Issue by larrybets** [platformio/platformio-atom-ide-terminal#536]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.27.1 x64
**Electron**: 1.7.15
**OS**: Unknown Windows version
**Thrown From**: [platformio-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) package 2.8.1

### Stack Trace

Uncaught TypeError: InputDialog is not a constructor

```
At C:\Users\Usuario\.atom\packages\platformio-ide-terminal\lib\view.coffee:529

TypeError: InputDialog is not a constructor
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.inputDialog (/packages/platformio-ide-terminal/lib/view.coffee:529:14)
    at /packages/platformio-ide-terminal/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLButtonElement.dispatch (/packages/platformio-ide-terminal/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/packages/platformio-ide-terminal/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -0:18.8.0 go-to-line:toggle (atom-text-editor.editor.is-focused)
     -0:08.6.0 platformio-ide-terminal:paste (textarea.)
```

### Non-Core Packages

```
angular-2-typeScript-snippets 0.7.0 
atom-bootstrap3 1.2.12 
atom-typescript 12.5.0 
color-picker 2.3.0 
emmet 2.4.3 
file-icons 2.1.21 
platformio-ide-terminal 2.8.1 
v-bootstrap4 0.2.2 
```

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0.
These type issues all so far seem fixed with this release due to using node-pty-prebuilt instead unmaintained and outdated pty.js
