### ISSUE TITLE
Uncaught Error: write EPIPE

### ISSUE THREAD

**Issue by ngocaovien** [platformio/platformio-atom-ide-terminal#553]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.27.2 x64
**Electron**: 1.7.15
**OS**: Microsoft Windows 10 Home
**Thrown From**: [platformio-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) package 2.8.2

### Stack Trace

Uncaught Error: write EPIPE

```
At events.js:163

Error: write EPIPE
    at exports._errnoException (util.js:1050:11)
    at ChildProcess.target._send (internal/child_process.js:676:20)
    at ChildProcess.target.send (internal/child_process.js:560:19)
    at Task.module.exports.Task.send (~/AppData/Local/atom/app-1.27.2/resources/app/src/task.js:113:33)
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.resize (/packages/platformio-ide-terminal/lib/view.coffee:276:17)
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.resizeTerminalToView (/packages/platformio-ide-terminal/lib/view.coffee:503:6)
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.focus (/packages/platformio-ide-terminal/lib/view.coffee:465:6)
    at PlatformIOTerminalView.focus (/packages/platformio-ide-terminal/lib/view.coffee:1:1)
    at /packages/platformio-ide-terminal/lib/status-bar.coffee:105:25
```

### Commands

```
     -0:55 window:toggle-full-screen (input.hidden-input)
     -0:52 window:toggle-menu-bar (input.hidden-input)
     -0:48.9.0 core:undo (input.hidden-input)
     -0:44 application:new-file (ul.list-inline.tab-bar.inset-panel)
     -0:41.4.0 core:undo (input.hidden-input)
     -0:39.7.0 window:toggle-full-screen (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.32.5 
atom-live-server 2.3.0 
emmet 2.4.3 
open-in-browser 0.5.2 
pigments 0.40.2 
platformio-ide-terminal 2.8.2 
```

**Comment by the-j0k3r** [comment]
@ngocaovien A possibility is to follow this portion https://flight-manual.atom.io/hacking-atom/sections/debugging/#reset-to-factory-defaults

Try to follow these steps after trying the step above to backup/reset Atom.

1. Make sure you upgrade to latest atom 1.29.0 Then install platformio-ide-terminal 2.8.4
2. try to duplicate.

Also try to ensure that issue is not being caused by some conflict with another Non-core package.

1. Install your Non-Core packages one at a time, testing to duplicate issue in between each non core package install

Notes: Ive run each command described and cant duplicate the issue above

```
C:\Users\Joker> atom -v

Atom    : 1.29.0
Electron: 2.0.5
Chrome  : 61.0.3163.100
Node    : 8.9.3

C:\Users\Joker> apm -v

apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.29.0
python 3.5.2
git 2.18.0.windows.1
visual studio
```

Windows 10 pro 1803/1709 64bit

**Comment by the-j0k3r** [comment]
Please retest with platformio-atom-ide-terminal 2.9.0
