### ISSUE TITLE
Uncaught Channel Closed

### ISSUE THREAD

**Issue by romanchl** [platformio/platformio-atom-ide-terminal#591]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.29.0 x64
**Electron**: 2.0.5
**OS**: Microsoft Windows 10 Home
**Thrown From**: [platformio-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) package 2.8.4

### Stack Trace

Uncaught channel closed

```
At events.js:183

Error [ERR_IPC_CHANNEL_CLOSED]: channel closed
    at ChildProcess.target.send (internal/child_process.js:588:16)
    at Task.module.exports.Task.send (~/AppData/Local/atom/app-1.29.0/resources/app/src/task.js:113:33)
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.resize (/packages/platformio-ide-terminal/lib/view.coffee:276:17)
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.resizeTerminalToView (/packages/platformio-ide-terminal/lib/view.coffee:503:6)
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.focus (/packages/platformio-ide-terminal/lib/view.coffee:465:6)
    at PlatformIOTerminalView.focus (/packages/platformio-ide-terminal/lib/view.coffee:1:1)
    at /packages/platformio-ide-terminal/lib/status-bar.coffee:105:25
```

### Commands

```
  2x -3:51.5.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
ask-stack 2.2.0 
atom-clock 0.1.16 
atom-runner 2.7.1 
busy-signal 1.4.3 
file-icons 2.1.24 
intentions 1.1.5 
linter 2.2.0 
linter-ui-default 1.7.1 
pigments 0.40.2 
platformio-ide-terminal 2.8.4 
```

**Comment by the-j0k3r** [comment]
dupliacte of https://github.com/platformio/platformio-atom-ide-terminal/issues/556

@ivankravets please close

@chlaps20 try what is described in https://github.com/platformio/platformio-atom-ide-terminal/issues/556#issuecomment-413263060 and respond to #556.

Thx
