### ISSUE TITLE
Uncaught channel closed

### ISSUE THREAD

**Issue by JasonCheng1** [platformio/platformio-atom-ide-terminal#604]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.30.0 x64
**Electron**: 2.0.5
**OS**: Microsoft Windows 10 Home
**Thrown From**: [platformio-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) package 2.8.4

### Stack Trace

Uncaught channel closed

```
At events.js:183

Error [ERR_IPC_CHANNEL_CLOSED]: channel closed
    at ChildProcess.target.send (internal/child_process.js:588:16)
    at Task.module.exports.Task.send (~/AppData/Local/atom/app-1.30.0/resources/app/src/task.js:113:33)
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.resize (/packages/platformio-ide-terminal/lib/view.coffee:276:17)
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.resizeTerminalToView (/packages/platformio-ide-terminal/lib/view.coffee:503:6)
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.focus (/packages/platformio-ide-terminal/lib/view.coffee:465:6)
    at PlatformIOTerminalView.focus (/packages/platformio-ide-terminal/lib/view.coffee:1:1)
    at /packages/platformio-ide-terminal/lib/view.coffee:80:12)
    at HTMLDivElement.dispatch (/packages/platformio-ide-terminal/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/platformio-ide-terminal/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
```

### Non-Core Packages

```
platformio-ide-terminal 2.8.4 
```

**Comment by CodeCurryCarma** [comment]
Facing similar issue !!!


Error [ERR_IPC_CHANNEL_CLOSED]: channel closed
    at ChildProcess.target.send (internal/child_process.js:588:16)
    at Task.module.exports.Task.send (C:\Users\Abhijit Jagadeesh\AppData\Local\atom\app-1.30.0\resources\app\src\task.js:113:33)
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.input (file:///C:/Users/Abhijit Jagadeesh/.atom/packages/platformio-ide-terminal/lib/view.coffee:271:17)
    at Terminal.<anonymous> (file:///C:/Users/Abhijit Jagadeesh/.atom/packages/platformio-ide-terminal/lib/view.coffee:149:8)
    at Terminal.EventEmitter.emit (C:\Users\Abhijit Jagadeesh\.atom\packages\platformio-ide-terminal\node_modules\term.js\src\term.js:109:12)
    at Terminal.handler (C:\Users\Abhijit Jagadeesh\.atom\packages\platformio-ide-terminal\node_modules\term.js\src\term.js:3493:8)
    at C:\Users\Abhijit Jagadeesh\.atom\packages\platformio-ide-terminal\node_modules\term.js\src\term.js:3253:12

**Comment by yastrebovb** [comment]
Similar issue
Error [ERR_IPC_CHANNEL_CLOSED]: channel closed
    at ChildProcess.target.send (internal/child_process.js:588:16)
    at Task.module.exports.Task.send (C:\Users\User\AppData\Local\atom\app-1.30.0\resources\app\src\task.js:113:33)
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.input (file:///C:/Users/User/.atom/packages/platformio-ide-terminal/lib/view.coffee:271:17)
    at Terminal.<anonymous> (file:///C:/Users/User/.atom/packages/platformio-ide-terminal/lib/view.coffee:149:8)
    at Terminal.EventEmitter.emit (C:\Users\User\.atom\packages\platformio-ide-terminal\node_modules\term.js\src\term.js:109:12)
    at Terminal.handler (C:\Users\User\.atom\packages\platformio-ide-terminal\node_modules\term.js\src\term.js:3493:8)
    at Terminal.keyPress (C:\Users\User\.atom\packages\platformio-ide-terminal\node_modules\term.js\src\term.js:3243:8)
    at HTMLDocument.<anonymous> (C:\Users\User\.atom\packages\platformio-ide-terminal\node_modules\term.js\src\term.js:608:29)

**Comment by quickank1t** [comment]
SImilar issue 

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.31.1 x64
**Electron**: 2.0.7
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [platformio-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) package 2.8.4


### Stack Trace

Uncaught channel closed

```
At events.js:183

Error [ERR_IPC_CHANNEL_CLOSED]: channel closed
    at ChildProcess.target.send (internal/child_process.js:588:16)
    at Task.module.exports.Task.send (~/AppData/Local/atom/app-1.31.1/resources/app/src/task.js:113:33)
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.resize (/packages/platformio-ide-terminal/lib/view.coffee:276:17)
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.resizeTerminalToView (/packages/platformio-ide-terminal/lib/view.coffee:503:6)
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.onWindowResize (/packages/platformio-ide-terminal/lib/view.coffee:390:6)
    at /packages/platformio-ide-terminal/lib/view.coffee:1:1
    at dispatch (/packages/platformio-ide-terminal/node_modules/jquery/dist/jquery.js:4435:9)
    at elemData.handle (/packages/platformio-ide-terminal/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -2:37.6.0 core:confirm (input.hidden-input)
     -2:11.2.0 core:save (input.hidden-input)
  2x -2:10.1.0 editor:newline (input.hidden-input)
     -2:07.2.0 autocomplete-plus:confirm (input.hidden-input)
     -2:07.2.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:03.1.0 core:backspace (input.hidden-input)
     -1:54.3.0 core:move-right (input.hidden-input)
     -1:53.3.0 core:move-left (input.hidden-input)
     -1:50.1.0 core:backspace (input.hidden-input)
     -1:49.4.0 core:save (input.hidden-input)
     -1:21.1.0 core:copy (input.hidden-input)
     -1:20.1.0 core:paste (input.hidden-input)
     -1:13.3.0 core:copy (input.hidden-input)
  2x -1:10.4.0 core:backspace (input.hidden-input)
     -1:10.1.0 core:paste (input.hidden-input)
     -1:01.5.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
platformio-ide-terminal 2.8.4 
react 0.18.0 
```

**Comment by lubohen** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.31.2 x64
**Electron**: 2.0.7
**OS**: Unknown Windows version
**Thrown From**: [platformio-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) package 2.8.4


### Stack Trace

Uncaught channel closed

```
At events.js:183

Error [ERR_IPC_CHANNEL_CLOSED]: channel closed
    at ChildProcess.target.send (internal/child_process.js:588:16)
    at Task.module.exports.Task.send (~/AppData/Local/atom/app-1.31.2/resources/app/src/task.js:113:33)
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.input (/packages/platformio-ide-terminal/lib/view.coffee:271:17)
    at /packages/platformio-ide-terminal/lib/view.coffee:149:8)
    at Terminal.EventEmitter.emit (/packages/platformio-ide-terminal/node_modules/term.js/src/term.js:109:12)
    at Terminal.handler (/packages/platformio-ide-terminal/node_modules/term.js/src/term.js:3493:8)
    at /packages/platformio-ide-terminal/node_modules/term.js/src/term.js:3253:12
```

### Commands

```
     -8:30.5.0 tree-view:add-file (span.name.icon.icon-file-directory)
 10x -8:27.3.0 core:backspace (input.hidden-input)
     -8:17.7.0 core:confirm (input.hidden-input)
     -8:12.1.0 tree-view:move (span.name.icon.default-icon)
     -8:09.2.0 core:confirm (input.hidden-input)
 33x -8:06.8.0 intentions:highlight (input.hidden-input)
     -8:05.4.0 platformio-ide-terminal:toggle (input.hidden-input)
  6x -6:39.4.0 core:confirm (textarea.)
     -5:58.8.0 core:backspace (input.hidden-input)
     -1:58.6.0 platformio-ide-terminal:toggle (div.tool-panel.tree-view)
```

### Non-Core Packages

```
atom-runner 2.7.1 
autocomplete-python 1.10.12 
busy-signal 1.4.3 
file-icons 2.1.25 
gloom 0.6.5 
intentions 1.1.5 
linter 2.2.0 
linter-pylama 0.10.1 
linter-ui-default 1.7.1 
MagicPython 1.1.1 
platformio-ide-terminal 2.8.4 
pretty-json 2.0.3 
```

**Comment by Fathi-S** [comment]
Any resolution for this issue?

**Comment by AlexPasqua** [comment]
No, for a bit it worked: the first time I used to open the terminal it was
working, but the other times it didn't (this happened after I installed
pywin). So, by closing and reopening Atom, the terminal used to work again.
Then I tried to install python 64bit but everything stopped working, so I
thought I could come back to the previous configuration (with python 32)
but nothing worked again.
So right now it doesn't work, never

Il lun 15 ott 2018, 00:20 Fathi-S <notifications@github.com> ha scritto:

**Comment by iamshubhamjaju** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.31.2 x64
**Electron**: 2.0.7
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: [platformio-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) package 2.8.4


### Stack Trace

Uncaught channel closed

```
At events.js:183

Error [ERR_IPC_CHANNEL_CLOSED]: channel closed
    at ChildProcess.target.send (internal/child_process.js:588:16)
    at Task.module.exports.Task.send (~/AppData/Local/atom/app-1.31.2/resources/app/src/task.js:113:33)
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.input (/packages/platformio-ide-terminal/lib/view.coffee:271:17)
    at /packages/platformio-ide-terminal/lib/view.coffee:149:8)
    at Terminal.EventEmitter.emit (/packages/platformio-ide-terminal/node_modules/term.js/src/term.js:109:12)
    at Terminal.handler (/packages/platformio-ide-terminal/node_modules/term.js/src/term.js:3493:8)
    at /packages/platformio-ide-terminal/node_modules/term.js/src/term.js:3253:12
```

### Commands

```
```

### Non-Core Packages

```
atom-clock 0.1.16 
atom-django 0.3.2 
autocomplete-python 1.10.12 
hey-pane 1.1.2 
Hydrogen 2.6.0 
platformio-ide-terminal 2.8.4 
```

**Comment by icmathad** [comment]
Plase help me I have assertion failed error 
<img width="960" alt="capture" src="https://user-images.githubusercontent.com/40857087/48062635-9dbef580-e1e8-11e8-8e87-1f9f3fa985d3.PNG">


events.js:183
Hide Stack Trace
Error [ERR_IPC_CHANNEL_CLOSED]: channel closed
    at ChildProcess.target.send (internal/child_process.js:588:16)
    at Task.t.exports.Task.send (C:\Users\Irayya\AppData\Local\atom\app-1.32.1\resources\app\static\<embedded>:14:37562)
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.resize (file:///C:/Users/Irayya/.atom/packages/platformio-ide-terminal/lib/view.coffee:276:17)
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.resizeTerminalToView (file:///C:/Users/Irayya/.atom/packages/platformio-ide-terminal/lib/view.coffee:503:6)
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.focus (file:///C:/Users/Irayya/.atom/packages/platformio-ide-terminal/lib/view.coffee:465:6)
    at PlatformIOTerminalView.focus (file:///C:/Users/Irayya/.atom/packages/platformio-ide-terminal/lib/view.coffee:1:1)
    at file:///C:/Users/Irayya/.atom/packages/platformio-ide-terminal/lib/view.coffee:190:26
    at HTMLDivElement.<anonymous> (file:///C:/Users/Irayya/.atom/packages/platformio-ide-terminal/lib/view.coffee:524:7)
    at HTMLDivElement.fn (C:\Users\Irayya\.atom\packages\platformio-ide-terminal\node_modules\jquery\dist\jquery.js:4855:19)
    at HTMLDivElement.dispatch (C:\Users\Irayya\.atom\packages\platformio-ide-terminal\node_modules\jquery\dist\jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (C:\Users\Irayya\.atom\packages\platformio-ide-terminal\node_modules\jquery\dist\jquery.js:4121:28)

**Comment by peasant98** [comment]
Facing similar issue, 
Uncaught channel closed
events.js:183.

**Comment by JacSjoerd** [comment]
Exact same issue on Windows 10 Enterprise edition.

**Comment by yteshi** [comment]
I am facing same issue on Windows 10 Home.

**Comment by AvidanGC** [comment]
Mismo problema windows 10 home:
events.js:183
Error [ERR_IPC_CHANNEL_CLOSED]: channel closed
    at ChildProcess.target.send (internal/child_process.js:588:16)
    at Task.t.exports.Task.send (C:\Users\avida\AppData\Local\atom\app-1.32.2\resources\app\static\<embedded>:14:37562)
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.input (file:///C:/Users/avida/.atom/packages/platformio-ide-terminal/lib/view.coffee:271:17)
    at Terminal.<anonymous> (file:///C:/Users/avida/.atom/packages/platformio-ide-terminal/lib/view.coffee:149:8)
    at Terminal.EventEmitter.emit (C:\Users\avida\.atom\packages\platformio-ide-terminal\node_modules\term.js\src\term.js:109:12)
    at Terminal.handler (C:\Users\avida\.atom\packages\platformio-ide-terminal\node_modules\term.js\src\term.js:3493:8)
    at C:\Users\avida\.atom\packages\platformio-ide-terminal\node_modules\term.js\src\term.js:3253:12
The error was thrown from the platformio-ide-terminal package. This issue has already been reported.
View Issue
![image](https://user-images.githubusercontent.com/7787528/48975226-e5cf7c00-f020-11e8-83e3-4b57134d3ec1.png)

**Comment by AyushBhargav** [comment]
I am also facing the same issue

**Comment by ManuelZ** [comment]
Same here.

**Comment by aufdenkampe** [comment]
A person I'm working with had the same error when Installing PlatformIO for Atom for the first time today, after also having the "Assertion Failed!" error (see https://github.com/platformio/platformio-atom-ide-terminal/issues/571). Are the two issues related?

**Comment by MartinCastellon** [comment]
No answers yet!?????

**Comment by mindwarrior** [comment]
Any alternative or workaround? Terminal-plus doesn't even seem to install? Is that also a known issue with windows 10 home?

**Comment by the-j0k3r** [comment]
try again with platformio-atom-ide-terminal 2.9.0 should be all fixed.

**Comment by the-j0k3r** [comment]
Also duplicate of #613 @ivankravets pls close.
