### ISSUE TITLE
slove this 

### ISSUE THREAD

**Issue by satwik13x** [platformio/platformio-atom-ide-terminal#615]
Error [ERR_IPC_CHANNEL_CLOSED]: channel closed
    at ChildProcess.target.send (internal/child_process.js:588:16)
    at Task.module.exports.Task.send (C:\Users\user\AppData\Local\atom\app-1.31.2\resources\app\src\task.js:113:33)
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.resize (file:///C:/Users/user/.atom/packages/platformio-ide-terminal/lib/view.coffee:276:17)
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.resizeTerminalToView (file:///C:/Users/user/.atom/packages/platformio-ide-terminal/lib/view.coffee:503:6)
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.focus (file:///C:/Users/user/.atom/packages/platformio-ide-terminal/lib/view.coffee:465:6)
    at PlatformIOTerminalView.focus (file:///C:/Users/user/.atom/packages/platformio-ide-terminal/lib/view.coffee:1:1)
    at file:///C:/Users/user/.atom/packages/platformio-ide-terminal/lib/status-bar.coffee:105:25

**Comment by jhollowe** [comment]
If you want this fixed, you will need to give more information on what you were doing when this happened, what version of Atom was running, what other packages you have, etc.

**Comment by the-j0k3r** [comment]
Fixed with 2.9.0 @ivankravets pls close.
