### ISSUE TITLE
Uncaught TypeError: Cannot set property 'innerHTML' of undefined

### ISSUE THREAD

**Issue by usui1** [platformio/platformio-atom-ide-terminal#624]
[Enter steps to reproduce:]

1. Open ide terminal
2. ssh to Mikrotik device
3. Press TAB

**Atom**: 1.32.1 x64
**Electron**: 2.0.9
**OS**: Ubuntu 18.04.1
**Thrown From**: [platformio-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) package 2.8.4

### Stack Trace

Uncaught TypeError: Cannot set property 'innerHTML' of undefined

```
At /home/usui/.atom/packages/platformio-ide-terminal/node_modules/term.js/src/term.js:1704

TypeError: Cannot set property 'innerHTML' of undefined
    at Terminal.refresh (/packages/platformio-ide-terminal/node_modules/term.js/src/term.js:1704:32)
    at Terminal.blur (/packages/platformio-ide-terminal/node_modules/term.js/src/term.js:519:8)
    at /packages/platformio-ide-terminal/node_modules/term.js/src/term.js:626:20)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-ftp-deployment 0.4.0 
atom-sublime-monokai-syntax 0.4.4 
auto-detect-indentation 1.3.0 
auto-indent 0.5.0 
busy-signal 1.4.3 
color-picker 2.3.0 
emmet 2.4.3 
file-icons 2.1.26 
git-plus 8.1.0 
intentions 1.1.5 
language-routeros-script 0.2.0 
linter 2.2.0 
linter-csslint 2.0.1 
linter-erb 1.1.1 
linter-js-standard 6.0.0 
linter-php 1.5.1 
linter-ruby 1.2.6 
linter-ui-default 1.7.1 
pinegrow-atom 0.3.1 
platformio-ide-terminal 2.8.4 
rails-snippets 2.19.0 
rails-transporter 1.7.1 
remote-ftp 2.2.0 
```

**Comment by the-j0k3r** [comment]
please upgrade to 2.9.0 should handle this better,

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js
