### ISSUE TITLE
Uncaught Error: Cannot find module '../src/term'

### ISSUE THREAD

**Issue by blakedias** [platformio/platformio-atom-ide-terminal#654]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Microsoft Windows 10 Home
**Thrown From**: [platformio-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) package 2.9.0

### Stack Trace

Uncaught Error: Cannot find module '../src/term'

```
At module.js:545

Error: Cannot find module '../src/term'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.34.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:154667)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:145974)
    at Function.Terminal (/packages/platformio-ide-terminal/node_modules/term.js/lib/index.js:48:27)
    at Function.module.exports.PlatformIOTerminalView.getFocusedTerminal (/packages/platformio-ide-terminal/lib/view.coffee:117:23)
    at /packages/platformio-ide-terminal/lib/status-bar.coffee:293:49
```

### Commands

```
     -0:25.8.0 open-in-browser:open (div.line)
```

### Non-Core Packages

```
emmet 2.4.3 
language-csv 1.1.2 
open-in-browser 0.5.2 
pigments 0.40.2 
platformio-ide-terminal 2.9.0 
```

**Comment by the-j0k3r** [comment]
Please fill in the required fields in the issue template. See this which you overwrote.
https://raw.githubusercontent.com/platformio/platformio-atom-ide-terminal/master/.github/ISSUE_TEMPLATE.md

**Comment by the-j0k3r** [comment]
Closing for lack of proper information and errors posted indicate a failure in download/installer, retry via apm and if it persists open a new report and fill in all required fields.

Term is a dependency of the project, cant control the download / installation of dependencies, people just have to retry or complain to apm.
