### ISSUE TITLE
platformio-ide-terminal 2.9.0                 Uncaught channel closed 

### ISSUE THREAD

**Issue by Flo082002** [platformio/platformio-atom-ide-terminal#657]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Windows 10
**Thrown From**: [platformio-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) package 2.9.0

### Stack Trace

Uncaught channel closed

```
At events.js:183

Error [ERR_IPC_CHANNEL_CLOSED]: channel closed
    at ChildProcess.target.send (internal/child_process.js:588:16)
    at Task.t.exports.Task.send (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:37562)
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.resize (/packages/platformio-ide-terminal/lib/view.coffee:276:17)
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.resizeTerminalToView (/packages/platformio-ide-terminal/lib/view.coffee:503:6)
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.focus (/packages/platformio-ide-terminal/lib/view.coffee:465:6)
    at PlatformIOTerminalView.focus (/packages/platformio-ide-terminal/lib/view.coffee:1:1)
    at /packages/platformio-ide-terminal/lib/view.coffee:190:26
    at /packages/platformio-ide-terminal/lib/view.coffee:524:7)
    at HTMLDivElement.fn (/packages/autocomplete-clang/node_modules/jquery/dist/jquery.js:4855:19)
    at HTMLDivElement.dispatch (/packages/autocomplete-clang/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/autocomplete-clang/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -2:23.8.0 core:save (atom-workspace.workspace.scrollbars-visible-always.theme-atom-material-syntax-dark.theme-atom-material-ui)
     -2:18.7.0 platformio-ide:target:upload (atom-workspace.workspace.scrollbars-visible-always.theme-atom-material-syntax-dark.theme-atom-material-ui)
     -2:18.7.0 platformio-ide:target:upload-C:\Users\Flo\Documents\PlatformIO\Projects\Uhr_library (atom-workspace.workspace.scrollbars-visible-always.theme-atom-material-syntax-dark.theme-atom-material-ui)
     -1:49.9.0 core:backspace (input.hidden-input)
undefined -1:45 intentions:highlight (input.hidden-input)
     -1:41.3.0 core:cut (input.hidden-input)
     -1:36.4.0 intentions:highlight (input.hidden-input)
     -1:35.9.0 core:paste (input.hidden-input)
     -1:26.2.0 platformio-ide:target:upload (input.hidden-input)
     -1:26.2.0 platformio-ide:target:upload-C:\Users\Flo\Documents\PlatformIO\Projects\Uhr_library (atom-workspace.workspace.scrollbars-visible-always.theme-atom-material-syntax-dark.theme-atom-material-ui)
     -1:03.5.0 editor:newline (input.hidden-input)
     -0:57.4.0 core:move-down (input.hidden-input)
     -0:57 autocomplete-plus:confirm (input.hidden-input)
     -0:50.7.0 platformio-ide:target:upload (input.hidden-input)
     -0:50.7.0 platformio-ide:target:upload-C:\Users\Flo\Documents\PlatformIO\Projects\Uhr_library (atom-workspace.workspace.scrollbars-visible-always.theme-atom-material-syntax-dark.theme-atom-material-ui)
  2x -0:28.2.0 platformio-ide:maintenance.serial-monitor (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.8 
atom-beautify 0.33.4 
atom-material-syntax 1.0.8 
atom-material-syntax-dark 1.0.0 
atom-material-syntax-light 0.4.6 
atom-material-ui 2.1.3 
auto-fold 0.4.0 
autocomplete-clang 0.11.5 
autocomplete-paths 2.12.2 
build 0.70.0 
busy-signal 2.0.0 
clock 1.9.1 
file-icons 2.1.29 
highlight-selected 0.14.0 
intentions 1.1.5 
language-ini 1.20.0 
language-rust 0.4.12 
linter 2.3.0 
linter-gcc 0.7.1 
linter-ui-default 1.7.1 
merge-conflicts 1.4.5 
minimap 4.29.9 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
pigments 0.40.2 
platformio-ide 2.3.1 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.9.0 
tool-bar 1.1.11 
uncrustify-0.68.1-win32 undefined 
```

**Comment by the-j0k3r** [comment]
Thank you for reaching out with this bug report.

You are getting this reply because the issue template was not filled in its entirety, overwritten,  or some portions were partially left out.

This issue template contains important information to be able to provide any kind of support, and will help us triage or reproduce the issue. Without reproduction no workaround or fix can normally be derived...

Copy and paste the template located at https://raw.githubusercontent.com/platformio/platformio-atom-ide-terminal/master/.github/ISSUE_TEMPLATE.md and fill in all fields. Logs / Errors / other information should be added at the bottom in the Notes portion of the [issue template](https://raw.githubusercontent.com/platformio/platformio-atom-ide-terminal/master/.github/ISSUE_TEMPLATE.md).

Tickets without this information may be closed and labeled invalid at our discretion.

Thank you for your understanding.
