### ISSUE TITLE
Uncaught Error: spawn EPERM

### ISSUE THREAD

**Issue by ayou129** [platformio/platformio-atom-ide-terminal#688]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.36.1 x64
**Electron**: 2.0.18
**OS**: Unknown Windows version
**Thrown From**: [platformio-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) package 2.9.1

### Stack Trace

Uncaught Error: spawn EPERM

```
At internal/child_process.js:323

Error: spawn EPERM
    at _errnoException (util.js:1024:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at exports.spawn (child_process.js:514:9)
    at Object.exports.fork (child_process.js:115:10)
    at new Task (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:14:35690)
    at Function.t.exports.Task.once (~/AppData/Local/atom/app-1.36.1/resources/app/static/<embedded>:14:36436)
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.forkPtyProcess (/packages/platformio-ide-terminal/lib/view.coffee:117:10)
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.displayTerminal (/packages/platformio-ide-terminal/lib/view.coffee:126:20)
    at /packages/platformio-ide-terminal/lib/view.coffee:231:10
    at /packages/platformio-ide-terminal/lib/view.coffee:524:7)
    at HTMLDivElement.fn (/packages/platformio-ide-terminal/node_modules/jquery/dist/jquery.js:4855:19)
    at HTMLDivElement.dispatch (/packages/platformio-ide-terminal/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/platformio-ide-terminal/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -0:24.5.0 intentions:highlight (input.hidden-input)
     -0:24.3.0 core:copy (input.hidden-input)
     -0:23.6.0 intentions:highlight (input.hidden-input)
     -0:23.5.0 core:paste (input.hidden-input)
     -0:21.1.0 intentions:highlight (input.hidden-input)
     -0:20.9.0 core:undo (input.hidden-input)
     -0:20.4.0 intentions:highlight (input.hidden-input)
     -0:20.2.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
busy-signal 2.0.1 
emmet 2.4.3 
file-icons 2.1.32 
intentions 1.1.5 
language-vue 0.24.0 
linter 2.3.0 
linter-eslint 8.5.5 
linter-ui-default 1.7.1 
platformio-ide-terminal 2.9.1 
sync-settings 0.8.6 
```

**Comment by the-j0k3r** [comment]
Thank you for reaching out with this bug report.

You are getting this reply because the issue template was not filled in its entirety, overwritten,  or some portions were partially left out.

This issue template contains important information to be able to provide any kind of support, and will help us triage or reproduce the issue. Without reproduction no workaround or fix can normally be derived...

Copy and paste the template located at https://raw.githubusercontent.com/platformio/platformio-atom-ide-terminal/master/.github/ISSUE_TEMPLATE.md and fill in all fields. Logs / Errors / other information should be added at the bottom in the Notes portion of the [issue template](https://raw.githubusercontent.com/platformio/platformio-atom-ide-terminal/master/.github/ISSUE_TEMPLATE.md).

Tickets without this information may be closed and labeled invalid at our discretion.

Thank you for your understanding.

**Comment by the-j0k3r** [comment]
Since there is no reply in 5 days, I will consider this issue resolved.

Please look at #668 for any workarounds if not, consider filling in our issue template **fully** and Ill reopen the ticket.
