### ISSUE TITLE
Uncaught TypeError: Cannot set property 'innerHTML' of undefined

### ISSUE THREAD

**Issue by RomanDanyk** [platformio/platformio-atom-ide-terminal#7]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.5.4
**System**: Ubuntu 15.10
**Thrown From**: [platformio-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) package, v2.0.3
### Stack Trace

Uncaught TypeError: Cannot set property 'innerHTML' of undefined

```
At /home/roman/.atom/packages/platformio-ide-terminal/node_modules/term.js/src/term.js:1704

TypeError: Cannot set property 'innerHTML' of undefined
    at Terminal.refresh (/home/roman/.atom/packages/platformio-ide-terminal/node_modules/term.js/src/term.js:1704:32)
    at Terminal.blur (/home/roman/.atom/packages/platformio-ide-terminal/node_modules/term.js/src/term.js:519:8)
    at HTMLDocument.<anonymous> (/home/roman/.atom/packages/platformio-ide-terminal/node_modules/term.js/src/term.js:626:20)
```
### Commands

```
  2x -1:35 core:backspace (atom-text-editor#platformio-ide-terminal.style.fontFamily.editor.mini.is-focused)
     -1:25.3.0 core:move-right (atom-text-editor#platformio-ide-terminal.style.fontSize.editor.mini.is-focused)
  4x -1:20 core:backspace (atom-text-editor#platformio-ide-terminal.style.fontSize.editor.mini.is-focused)
     -1:04.8.0 core:move-up (atom-text-editor#platformio-ide-terminal.style.fontSize.editor.mini.is-focused)
     -0:50 core:backspace (atom-text-editor#platformio-ide-terminal.style.fontSize.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "vim-mode",
      "terminal-plus",
      "atom-terminal-panel"
    ]
  },
  "platformio-ide-terminal": {
    "core": {},
    "style": {
      "fontFamily": "monospace",
      "fontSize": "10"
    },
    "toggles": {
      "autoClose": true
    }
  }
}
```
### Installed Packages

``` coffee
# User
color-picker, v2.1.1
minimap, v4.21.0
pigments, v0.24.5
platformio-ide-terminal, v2.0.3
terminal-panel, v1.14.1

# Dev
No dev packages
```
##

**Comment by ivankravets** [comment]
@RomanDanyk how to reproduce it? Does it mean that you can not launch Terminal?

**Comment by RomanDanyk** [comment]
Hi @ivankravets,
No, I can launch Terminal. I get this error when connect from Terminal via ssh to Mikrotik.

**Comment by ivankravets** [comment]
Currently we are focussed on the issues related to @PlatformIO ecosystem. We take a look at it when will have a free time or maybe someone will help us.

Thanks a lot for understanding.

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js
