### ISSUE TITLE
platform-ide-terminal giving this error

### ISSUE THREAD

**Issue by grasscannoli** [platformio/platformio-atom-ide-terminal#725]
- [x] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Description

It has been working very well for over two months (since I had previously installed it). It has kept giving this error given in the "Additional information section", at the end, in the debugger/upon pressing the "bug" icon at the bottom right corner. I have now tried to uninstall and reinstall it but it gives an error and refuses to install. The error seems to look like its the same. (The error given at the end is the output it gives after it breaks from installing)

### Steps to reproduce

1. Direct issue pointed to by the debugger. Or if I try to reinstall it.

**Expected behavior:** 
Find the terminal '+' symbol at the bottom left corner. Pressing it gives me the terminal ide.

**Actual behavior:** 
Debugger reports a problem with the package.
Also no '+' symbol at the bottom.

**Reproduces how often:** 
100%

### Versions

```
> atom --version
```
```
Atom    : 1.39.0
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0
```
```
> apm --version
```
```
apm  2.2.4
npm  6.2.0
node 8.9.3 x64
atom 1.39.0
python 3.7.3
git
visual studio
```
OS name and version: Windows 10
Platformio-ide-terminal version: 2.9.1

### Additional Information

```
> node-pty-prebuilt@0.7.6 install C:\Users\grass\AppData\Local\Temp\apm-install-dir-119625-16148-14pb4ys.kwhl\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt
> prebuild-install || node scripts/install.js


C:\Users\grass\AppData\Local\Temp\apm-install-dir-119625-16148-14pb4ys.kwhl\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt>if not defined npm_config_node_gyp (node "C:\Users\grass\AppData\Local\atom\app-1.39.0\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --build_v8_with_gn=false )  else (node "C:\Users\grass\AppData\Local\atom\app-1.39.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild --build_v8_with_gn=false ) 

prebuild-install WARN install No prebuilt binaries found (target=3.1.10 runtime=electron arch=x64 libc= platform=win32)
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "C:\Users\grass\Anaconda3\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\grass\AppData\Local\atom\app-1.39.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\configure.js:492:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\grass\AppData\Local\atom\app-1.39.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\configure.js:517:16)
gyp ERR! stack     at C:\Users\grass\AppData\Local\atom\app-1.39.0\resources\app\apm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Users\\grass\\AppData\\Local\\atom\\app-1.39.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\grass\\AppData\\Local\\atom\\app-1.39.0\\resources\\app\\apm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--build_v8_with_gn=false"
gyp ERR! cwd C:\Users\grass\AppData\Local\Temp\apm-install-dir-119625-16148-14pb4ys.kwhl\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\grass\AppData\Local\Temp\apm-install-dir-119625-16148-14pb4ys.kwhl\package.json'
npm WARN apm-install-dir-119625-16148-14pb4ys.kwhl No description
npm WARN apm-install-dir-119625-16148-14pb4ys.kwhl No repository field.
npm WARN apm-install-dir-119625-16148-14pb4ys.kwhl No README data
npm WARN apm-install-dir-119625-16148-14pb4ys.kwhl No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty-prebuilt@0.7.6 install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty-prebuilt@0.7.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\grass\.atom\.apm\_logs\2019-07-25T09_22_28_065Z-debug.log
```

**Comment by veduardoe** [comment]
I have the same error.
The day after yesterday was working fine, then I don't know what's happening.

**Comment by the-j0k3r** [comment]
Thank you for reaching ou to use with this issue report.

Many duplicates to #700 have been filed including yours, including me too reports

There is a workaround, its been posted in this issue https://github.com/platformio/platformio-atom-ide-terminal/issues/707#issuecomment-514634895 < click that.

Thanks for your understanding.
