### ISSUE TITLE
Uncaught TypeError: Cannot set property '1' of undefined

### ISSUE THREAD

**Issue by lunli-econ** [platformio/platformio-atom-ide-terminal#790]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.6
**Thrown From**: [platformio-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) package 2.9.4

### Stack Trace

Uncaught TypeError: Cannot set property '1' of undefined

```
At /Users/lunl/.atom/packages/platformio-ide-terminal/node_modules/term.js/src/term.js:1939

TypeError: Cannot set property '1' of undefined
    at Terminal.write (/packages/platformio-ide-terminal/node_modules/term.js/src/term.js:1939:55)
    at /packages/platformio-ide-terminal/lib/view.coffee:141:17
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:43334
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1209208)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1210649)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:42435)
    at ChildProcess.emit (events.js:182:13)
    at emit (internal/child_process.js:811:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

### Commands

```
     -6:37.2.0 core:move-right (input.hidden-input)
     -6:36.8.0 editor:move-to-end-of-screen-line (input.hidden-input)
 10x -6:36.4.0 core:backspace (input.hidden-input)
     -6:33.5.0 core:save (input.hidden-input)
     -5:30.2.0 editor:newline (input.hidden-input)
     -5:29.3.0 core:move-up (input.hidden-input)
  9x -5:26.7.0 core:backspace (input.hidden-input)
     -5:21.4.0 core:move-right (input.hidden-input)
     -5:19.6.0 platformio-ide-terminal:insert-selected-text (input.hidden-input)
  4x -3:53.4.0 core:move-up (input.hidden-input)
  4x -3:52.6.0 core:move-down (input.hidden-input)
     -3:51.7.0 editor:move-to-first-character-of-line (input.hidden-input)
     -3:51.3.0 editor:select-to-end-of-line (input.hidden-input)
     -3:50.7.0 core:copy (input.hidden-input)
  2x -3:46.2.0 editor:newline (input.hidden-input)
 13x -3:45.4.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-language-r 1.4.8 
language-markdown 0.37.0 
monokai 0.24.0 
platformio-ide-terminal 2.9.4 
```

**Comment by the-j0k3r** [comment]
This error for term.js is non specific, also term.js its an abandoned(no longer developed) project dependency.

There is nothing we can do here except implement #426 but because of #543 all contributions have to come from external contributors

Sorry for any inconvenience this may cause, Ill just mark this as wontfix because theres no maintainers to address #426 at this time, unless some come forth.

Thanks for understanding.
