### ISSUE TITLE
Cannot open "VM22 <embedded>:14 Cannot read property 'SOCKET' of undefined TypeError: Cannot read property 'SOCKET' of undefined"

### ISSUE THREAD

**Issue by asdf23** [platformio/platformio-atom-ide-terminal#813]
```
When opening the terminal I get this error:
VM22 <embedded>:14 Cannot read property 'SOCKET' of undefined TypeError: Cannot read property 'SOCKET' of undefined

VM22 <embedded>:14 Cannot read property 'SOCKET' of undefined TypeError: Cannot read property 'SOCKET' of undefined
    at new PipeSocket (/home/user/.atom/packages/platformio-ide-terminal/node_modules/node-pty-prebuilt-multiarch/lib/unixTerminal.js:259:41)
    at new UnixTerminal (/home/user/.atom/packages/platformio-ide-terminal/node_modules/node-pty-prebuilt-multiarch/lib/unixTerminal.js:87:25)
    at Object.fork (/home/user/.atom/packages/platformio-ide-terminal/node_modules/node-pty-prebuilt-multiarch/lib/index.js:33:12)
    at Object.module.exports (/home/user/.atom/packages/platformio-ide-terminal/lib/process.coffee:25:22)
    at process.<anonymous> (/usr/share/atom/resources/app.asar/src/task-bootstrap.js:51:41)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by chakibBH** [comment]
Hi
I've got the same logged error here.

Adding versions if it help:
```
$ apm --version
>
apm  2.1.2
npm  6.2.0
node 8.9.3 x64
atom 1.33.1
python 2.7.17
git 2.17.1

$ atom --version
>
Atom    : 1.33.1
Electron: 2.0.16
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

As stated by @the-j0k3r 's [comment](https://github.com/platformio/platformio-atom-ide-terminal/issues/770#issuecomment-523299626), updating atom and reinstalling the platformio package resolved the issue
