### ISSUE TITLE
Install Issue. 2.10.0 on Windows 10

### ISSUE THREAD

**Issue by ParkDerkYoul** [platformio/platformio-atom-ide-terminal#822]
Hi.
How do I solve this problem?

`>apm --version
apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.43.0
python 2.7.15
git 2.21.0.windows.1
visual studio

C:\Users\pdy\AppData\Local\Temp\apm-install-dir-120029-10876-tzd5gf.v0g6c\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch>if not defined npm_config_node_gyp (node "C:\Users\pdy\AppData\Local\atom\app-1.43.0\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\pdy\AppData\Local\atom\app-1.43.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 

prebuild-install WARN install unexpected end of file
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Traceback (most recent call last):
  File "C:\Users\pdy\AppData\Local\atom\app-1.43.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "C:\Users\pdy\AppData\Local\atom\app-1.43.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "C:\Users\pdy\AppData\Local\atom\app-1.43.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "C:\Users\pdy\AppData\Local\atom\app-1.43.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "C:\Users\pdy\AppData\Local\atom\app-1.43.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 2004, in GenerateOutput
    generator_flags))
  File "C:\Users\pdy\AppData\Local\atom\app-1.43.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 943, in _GenerateProject
    return _GenerateMSVSProject(project, options, version, generator_flags)
  File "C:\Users\pdy\AppData\Local\atom\app-1.43.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1047, in _GenerateMSVSProject
    p.WriteIfChanged()
  File "C:\Users\pdy\AppData\Local\atom\app-1.43.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\MSVSProject.py", line 208, in WriteIfChanged
    encoding="Windows-1252")
  File "C:\Users\pdy\AppData\Local\atom\app-1.43.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\easy_xml.py", line 122, in WriteXmlIfChanged
    xml_string = xml_string.decode(default_encoding).encode(encoding)
  File "C:\Python27\lib\encodings\cp1252.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode characters in position 501-503: character maps to <undefined>
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1

**Comment by Falamansa** [comment]
I'm having the same error.
