### ISSUE TITLE
Failed to activate the platformio-ide-terminal package

### ISSUE THREAD

**Issue by BismarckY** [platformio/platformio-atom-ide-terminal#836]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.3
**Thrown From**: [platformio-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) package 2.10.0

### Stack Trace

Failed to activate the platformio-ide-terminal package

```
At Cannot find module 'atom-space-pen-views'

Error: Cannot find module 'atom-space-pen-views'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:155413)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/platformio-ide-terminal/lib/status-bar.coffee:2:13)
    at /packages/platformio-ide-terminal/lib/status-bar.coffee:1:1)
    at /packages/platformio-ide-terminal/lib/status-bar.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at Object.consumeStatusBar (/packages/platformio-ide-terminal/lib/platformio-ide-terminal.coffee:28:27)
    at Provider.provide (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1122126)
    at ServiceHub.consume (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3217026)
    at Package.activateServices (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3225258)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3222013)
    at string.e.trim.length.activationHookSubscriptions.add.packageManager.onDidTriggerActivationHook (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2607)
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1214120)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1215561)
    at PackageManager.triggerDeferredActivationHooks (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:382896)
    at activatePromise.Promise.all.then (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:381647)
```

### Commands

```
     -0:18.8.0 window:install-shell-commands (atom-pane.pane)
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
git-plus 8.7.1 
git-plus-toolbar 1.0.1 
go-debug 1.7.0 
go-plus 6.1.0 
go-signature-statusbar 1.2.3 
Hydrogen 2.14.0 
ide-golang 0.0.5 
language-markdown 0.37.0 
linter 2.3.1 
markdown-pdf 2.2.0 
markdown-writer 2.11.9 
platformio-ide-terminal 2.10.0 
platformio-ide-terminal 2.10.0 
tool-bar 1.2.2 
```

**Comment by Moklite** [comment]
C:\Users\HP\.atom\packages\platformio-atom-ide-terminal-2.10.0

**Comment by Yasery** [comment]
Any update on this issue ?

**Comment by the-j0k3r** [comment]
> Any update on this issue ?

the op has
platformio-ide-terminal 2.10.0 
platformio-ide-terminal 2.10.0 

the package sowing twice is a tell tale sign of bad install/upgrade
Its apm throwing a fit

FYI you cannot and should not have any terminals open when upgrading/updating the program itself. APM will break the install because of locked files in use.

INSTALL/Upgrade issues are apm domain, no point reporting it here.

**Comment by the-j0k3r** [comment]
Use https://github.com/bus-stop/x-terminal or https://github.com/bus-stop/terminus
