### ISSUE TITLE
Uncaught Error: Cannot find module '../src/term'Require stack:- $ATOM_HOME/packages\platformio-...

### ISSUE THREAD

**Issue by ayodejid1** [platformio/platformio-atom-ide-terminal#861]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.47.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [platformio-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) package 2.10.0

### Stack Trace

Uncaught Error: Cannot find module '../src/term'
Require stack:
- C:\Users\AYODEJI\.atom\packages\platformio-ide-terminal\node_modules\term.js\lib\index.js
- C:\Users\AYODEJI\.atom\packages\platformio-ide-terminal\node_modules\term.js\index.js
- C:\Users\AYODEJI\.atom\packages\platformio-ide-terminal\lib\view.coffee
- C:\Users\AYODEJI\.atom\packages\platformio-ide-terminal\lib\status-bar.coffee
- C:\Users\AYODEJI\.atom\packages\platformio-ide-terminal\lib\platformio-ide-terminal.coffee
- C:\Users\AYODEJI\AppData\Local\atom\app-1.47.0\resources\app.asar\static\index.html

```
At internal/modules/cjs/loader.js:686

Error: Cannot find module '../src/term'
Require stack:
- C:\Users\AYODEJI\.atom\packages\platformio-ide-terminal\node_modules\term.js\lib\index.js
- C:\Users\AYODEJI\.atom\packages\platformio-ide-terminal\node_modules\term.js\index.js
- C:\Users\AYODEJI\.atom\packages\platformio-ide-terminal\lib\view.coffee
- C:\Users\AYODEJI\.atom\packages\platformio-ide-terminal\lib\status-bar.coffee
- C:\Users\AYODEJI\.atom\packages\platformio-ide-terminal\lib\platformio-ide-terminal.coffee
- C:\Users\AYODEJI\AppData\Local\atom\app-1.47.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:683:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.47.0/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:155434)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:146766)
    at Function.Terminal (/packages/platformio-ide-terminal/node_modules/term.js/lib/index.js:48:27)
    at /packages/platformio-ide-terminal/node_modules/term.js/lib/index.js:8:19)
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.displayTerminal (/packages/platformio-ide-terminal/lib/view.coffee:266:23)
    at /packages/platformio-ide-terminal/lib/view.coffee:417:19
    at /packages/platformio-ide-terminal/lib/view.coffee:788:11)
    at HTMLDivElement.fn (/packages/platformio-ide-terminal/node_modules/jquery/dist/jquery.js:4855:19)
    at HTMLDivElement.dispatch (/packages/platformio-ide-terminal/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/platformio-ide-terminal/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -1:53.4.0 application:open-folder (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:12.9.0 pane:reopen-closed-item (input.hidden-input)
     -0:57.7.0 platformio-ide-terminal:new (input.hidden-input)
     -0:17.4.0 core:save (input.hidden-input)
  3x -0:09.4.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-clang 0.13.1 
autocomplete-python 1.16.0 
build 0.70.0 
busy-signal 2.0.1 
file-icons 2.1.41 
intentions 1.1.5 
language-ini 1.23.0 
linter 2.3.1 
linter-gcc2 0.8.8 
linter-ui-default 1.8.1 
platformio-ide 2.6.0 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.10.0 
tool-bar 1.3.0 
```

**Comment by the-j0k3r** [comment]
Try https://github.com/bus-stop/terminus

This was instalation issue, it has nothing to do with terminal.
