### ISSUE TITLE
Uncaught Error: Cannot find module './input-dialog'Require stack:- $ATOM_HOME/packages\platform...

### ISSUE THREAD

**Issue by roman1117459** [platformio/platformio-atom-ide-terminal#866]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.47.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Pro Education
**Thrown From**: [platformio-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) package 2.10.0

### Stack Trace

Uncaught Error: Cannot find module './input-dialog'
Require stack:
- C:\Users\DCL\.atom\packages\platformio-ide-terminal\lib\view.coffee
- C:\Users\DCL\.atom\packages\platformio-ide-terminal\lib\status-bar.coffee
- C:\Users\DCL\.atom\packages\platformio-ide-terminal\lib\platformio-ide-terminal.coffee
- C:\Users\DCL\AppData\Local\atom\app-1.47.0\resources\app.asar\static\index.html

```
At internal/modules/cjs/loader.js:686

Error: Cannot find module './input-dialog'
Require stack:
- C:\Users\DCL\.atom\packages\platformio-ide-terminal\lib\view.coffee
- C:\Users\DCL\.atom\packages\platformio-ide-terminal\lib\status-bar.coffee
- C:\Users\DCL\.atom\packages\platformio-ide-terminal\lib\platformio-ide-terminal.coffee
- C:\Users\DCL\AppData\Local\atom\app-1.47.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:683:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.47.0/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:155434)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:146766)
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.inputDialog (/packages/platformio-ide-terminal/lib/view.coffee:797:23)
    at /packages/platformio-ide-terminal/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLButtonElement.dispatch (/packages/platformio-ide-terminal/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/packages/platformio-ide-terminal/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -1:22.1.0 platformio-ide-terminal:copy (div.)
```

### Non-Core Packages

```
atom-django 0.3.2 
atom-python-run 0.9.7 
autocomplete-python 1.16.0 
ide-python 1.5.0 
platformio-ide-terminal 2.10.0 
python-debugger 0.2.0 
script 3.26.0 
```

**Comment by the-j0k3r** [comment]
Try https://github.com/bus-stop/terminus
