### ISSUE TITLE
Uncaught Error: Cannot find module '../src/term'Require stack:- $ATOM_HOME/packages/platformio-...

### ISSUE THREAD

**Issue by julianrirau** [platformio/platformio-atom-ide-terminal#873]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.48.0 x64
**Electron**: 5.0.13
**OS**: Mac OS X 10.15.4
**Thrown From**: [platformio-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) package 2.10.0

### Stack Trace

Uncaught Error: Cannot find module '../src/term'
Require stack:
- /Users/julian/.atom/packages/platformio-ide-terminal/node_modules/term.js/lib/index.js
- /Users/julian/.atom/packages/platformio-ide-terminal/node_modules/term.js/index.js
- /Users/julian/.atom/packages/platformio-ide-terminal/lib/view.coffee
- /Users/julian/.atom/packages/platformio-ide-terminal/lib/status-bar.coffee
- /Users/julian/.atom/packages/platformio-ide-terminal/lib/platformio-ide-terminal.coffee
- /private/var/folders/2y/lpwsc0nd37v5tyj5rpl20y940000gn/T/AppTranslocation/390933EA-F481-43E6-87D7-B184BD1033CA/d/Atom.app/Contents/Resources/app.asar/static/index.html

```
At internal/modules/cjs/loader.js:686

Error: Cannot find module '../src/term'
Require stack:
- /Users/julian/.atom/packages/platformio-ide-terminal/node_modules/term.js/lib/index.js
- /Users/julian/.atom/packages/platformio-ide-terminal/node_modules/term.js/index.js
- /Users/julian/.atom/packages/platformio-ide-terminal/lib/view.coffee
- /Users/julian/.atom/packages/platformio-ide-terminal/lib/status-bar.coffee
- /Users/julian/.atom/packages/platformio-ide-terminal/lib/platformio-ide-terminal.coffee
- /private/var/folders/2y/lpwsc0nd37v5tyj5rpl20y940000gn/T/AppTranslocation/390933EA-F481-43E6-87D7-B184BD1033CA/d/Atom.app/Contents/Resources/app.asar/static/index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:683:15)
    at Module._resolveFilename (/private/var/folders/2y/lpwsc0nd37v5tyj5rpl20y940000gn/T/AppTranslocation/390933EA-F481-43E6-87D7-B184BD1033CA/d/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (/private/var/folders/2y/lpwsc0nd37v5tyj5rpl20y940000gn/T/AppTranslocation/390933EA-F481-43E6-87D7-B184BD1033CA/d/Atom.app/Contents/Resources/app/static/<embedded>:11:155487)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (/private/var/folders/2y/lpwsc0nd37v5tyj5rpl20y940000gn/T/AppTranslocation/390933EA-F481-43E6-87D7-B184BD1033CA/d/Atom.app/Contents/Resources/app/static/<embedded>:11:146819)
    at Function.Terminal (/packages/platformio-ide-terminal/node_modules/term.js/lib/index.js:48:27)
    at /packages/platformio-ide-terminal/node_modules/term.js/lib/index.js:8:19)
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.displayTerminal (/packages/platformio-ide-terminal/lib/view.coffee:138:17)
    at /packages/platformio-ide-terminal/lib/view.coffee:241:10
    at /packages/platformio-ide-terminal/lib/view.coffee:539:7)
    at HTMLDivElement.fn (/packages/platformio-ide-terminal/node_modules/jquery/dist/jquery.js:4855:19)
    at HTMLDivElement.dispatch (/packages/platformio-ide-terminal/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/platformio-ide-terminal/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -1:01.8.0 autocomplete-plus:confirm (input.hidden-input)
  2x -1:00.9.0 core:move-right (input.hidden-input)
     -0:59.8.0 core:backspace (input.hidden-input)
     -0:59.6.0 editor:newline (input.hidden-input)
  9x -0:57.6.0 core:backspace (input.hidden-input)
     -0:42.1.0 core:move-right (input.hidden-input)
  4x -0:40.1.0 core:move-left (input.hidden-input)
     -0:39 core:move-up (input.hidden-input)
  6x -0:38.7.0 core:move-left (input.hidden-input)
 10x -0:36.5.0 core:move-right (input.hidden-input)
     -0:32.4.0 core:move-down (input.hidden-input)
 10x -0:31.9.0 core:move-left (input.hidden-input)
  9x -0:28.4.0 core:move-right (input.hidden-input)
     -0:20.6.0 editor:newline (input.hidden-input)
     -0:17.9.0 editor:delete-to-beginning-of-word (input.hidden-input)
  4x -0:17.7.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
platformio-ide-terminal 2.10.0 
```

**Comment by guos001** [comment]
i have the same problem

**Comment by the-j0k3r** [comment]
Try https://github.com/bus-stop/terminus
