### ISSUE TITLE
Unable to install platformio-ide-terminal in Atom

### ISSUE THREAD

**Issue by Indranil2501** [platformio/platformio-atom-ide-terminal#910]
- [✓] I have reset Atom to defaults prior to submitting a report.

### Description
I am a beginner in python and just started learning it since yesterday and I was facing this error:
```
Installing “platformio-ide-terminal@2.10.0” failed.

> node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install C:\Users\***\AppData\Local\Temp\apm-install-dir-2020914-12224-l2dhgv.ez4lo\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt- 
multiarch
> prebuild-install || node scripts/install.js

C:\Users\***\AppData\Local\Temp\apm-install-dir-2020914-12224-l2dhgv.ez4lo\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch>if not defined npm_config_node_gyp (node "C:\Users\***\AppData\Local\atom\app-1.52.0\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\***\AppData\Local\atom\app-1.52.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:\Users\***\AppData\Local\Temp\apm-install-dir-2020914-12224-l2dhgv.ez4lo\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\conpty.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:\Users\***\AppData\Local\Temp\apm-install-dir-2020914-12224-l2dhgv.ez4lo\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\conpty_console_list.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:\Users\***\AppData\Local\Temp\apm-install-dir-2020914-12224-l2dhgv.ez4lo\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\deps\winpty\src\winpty.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:\Users\***\AppData\Local\Temp\apm-install-dir-2020914-12224-l2dhgv.ez4lo\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\deps\winpty\src\winpty-agent.vcxproj]

prebuild-install WARN install No prebuilt binaries found (target=6.1.12 runtime=electron arch=x64 libc= platform=win32)
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\***\AppData\Local\atom\app-1.52.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Users\\***\\AppData\\Local\\atom\\app-1.52.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\indra\\AppData\\Local\\atom\\app-1.52.0\\resources\\app\\apm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\***\AppData\Local\Temp\apm-install-dir-2020914-12224-l2dhgv.ez4lo\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch
gyp ERR! node -v v12.4.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\indra\AppData\Local\Temp\apm-install-dir-2020914-12224-l2dhgv.ez4lo\package.json'
npm WARN apm-install-dir-2020914-12224-l2dhgv.ez4lo No description
npm WARN apm-install-dir-2020914-12224-l2dhgv.ez4lo No repository field.
npm WARN apm-install-dir-2020914-12224-l2dhgv.ez4lo No README data
npm WARN apm-install-dir-2020914-12224-l2dhgv.ez4lo No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\***\.atom\.apm\_logs\2020-10-14T12_05_28_400Z-debug.log
```

### Steps to reproduce
1. Install Atom in your PC
2. Install platformio-ide-terminal in Atom

**Expected behavior:** platformio-ide-terminalshould be installed

**Actual behavior:** platformio-ide-terminal is not installed

**Reproduces how often:** Everytime

### Versions

```
> atom --version: 1.52.0

```
```
> platformio-ide-terminal--version: 2.10.0

```

OS name and version: Windows 10

**Comment by drewbaker** [comment]
Same on Mac for me!

**Comment by undercertainty** [comment]
Yes, me too. Also on Mac (Catalina 10.15.7).

**Comment by ivankravets** [comment]
Fixed in https://github.com/platformio/platformio-atom-ide-terminal/releases/tag/v2.10.1

Please update `platformio-ide-terminal` to the latest version.
