### ISSUE TITLE
platformio-ide-terminal@2.10.0 failed

### ISSUE THREAD

**Issue by NotSudoNym** [platformio/platformio-atom-ide-terminal#926]
- [x ] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Description
Unable to install Platform IDE Terminal 2.10.0

### Steps to reproduce
Open Atom on Windows > File > Settings > Install > Install platformio-ide-terminal@2.10.0

**Expected behavior:**  
Installs

**Actual behavior:** 
Fails with error

**Reproduces how often:** 
Every time. 

### Versions
```
> atom --version
1.52.0
```
```
> apm --version
Using Atom to install
```
OS name and version: Windows 10 version 1909 
Platformio-ide-terminal version:2.10.0

### Additional Information
prebuild-install WARN install No prebuilt binaries found (target=6.1.12 runtime=electron arch=x64 libc= platform=win32)
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\Visual Studio Enterprise 2019\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Dami\AppData\Local\atom\app-1.52.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Users\\Dami\\AppData\\Local\\atom\\app-1.52.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Dami\\AppData\\Local\\atom\\app-1.52.0\\resources\\app\\apm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Dami\AppData\Local\Temp\apm-install-dir-2020922-14748-161p03d.8iib\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch
gyp ERR! node -v v12.4.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Dami\AppData\Local\Temp\apm-install-dir-2020922-14748-161p03d.8iib\package.json'
npm WARN apm-install-dir-2020922-14748-161p03d.8iib No description
npm WARN apm-install-dir-2020922-14748-161p03d.8iib No repository field.
npm WARN apm-install-dir-2020922-14748-161p03d.8iib No README data
npm WARN apm-install-dir-2020922-14748-161p03d.8iib No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by NotSudoNym** [comment]
Installed terminus instead.
