### ISSUE TITLE
Failed to activate platformio-ide-termina

### ISSUE THREAD

**Issue by omcyrus** [platformio/platformio-atom-ide-terminal#939]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.52.0 ia32
**Electron**: 6.1.12
**OS**: Unknown Windows version
**Thrown From**: [platformio-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) package 2.10.0

### Stack Trace

Failed to activate the platformio-ide-terminal package

```
At Cannot find module 'atom-space-pen-views'
Require stack:
- C:\Users\JKS\.atom\packages\platformio-ide-terminal\lib\status-bar.coffee
- C:\Users\JKS\.atom\packages\platformio-ide-terminal\lib\platformio-ide-terminal.coffee
- C:\Users\JKS\AppData\Local\atom\app-1.52.0\resources\app.asar\static\index.html

Error: Cannot find module 'atom-space-pen-views'
Require stack:
- C:\Users\JKS\.atom\packages\platformio-ide-terminal\lib\status-bar.coffee
- C:\Users\JKS\.atom\packages\platformio-ide-terminal\lib\platformio-ide-terminal.coffee
- C:\Users\JKS\AppData\Local\atom\app-1.52.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.52.0/resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:155481)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:146814)
    at /packages/platformio-ide-terminal/lib/status-bar.coffee:2:13)
    at /packages/platformio-ide-terminal/lib/status-bar.coffee:1:1)
    at /packages/platformio-ide-terminal/lib/status-bar.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:147498)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:146814)
    at Object.consumeStatusBar (/packages/platformio-ide-terminal/lib/platformio-ide-terminal.coffee:28:27)
    at Provider.provide (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:14:1086071)
    at ServiceHub.consume (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:3286972)
    at Package.activateServices (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:3295256)
    at Package.activateNow (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:3292011)
    at ~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:14:2607
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:1190511)
    at Emitter.emit (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:1191952)
    at PackageManager.triggerDeferredActivationHooks (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:383664)
    at ~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:382415
```

### Commands

```
```

### Non-Core Packages

```
atom-html-preview 0.2.6 
gcc-make-run 0.2.12 
platformio-ide-terminal 2.10.0 
script 3.26.0 
```

**Comment by the-j0k3r** [comment]
try https://atom.io/packages/terminus

**Comment by ivankravets** [comment]
Fixed in https://github.com/platformio/platformio-atom-ide-terminal/releases/tag/v2.10.1

Please update `platformio-ide-terminal` to the latest version.
