### ISSUE TITLE
I can't install this. I've had this problem for several weeks.

### ISSUE THREAD

**Issue by derickmoncado** [platformio/platformio-atom-ide-terminal#947]
- [x ] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Steps to reproduce

1. Click install, that's literally it.
2.
3.

**Expected behavior:** 

**Actual behavior:** 
```
Installing “platformio-ide-terminal@2.10.0” failed.Hide output…

> node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install /private/var/folders/tl/szr40tn97_q9jb_ylcrxt_4w0000gn/T/apm-install-dir-2020931-1647-65g17y.un6ck/node_modules/platformio-ide-terminal/node_modules/node-pty-prebuilt-multiarch
> prebuild-install || node scripts/install.js


prebuild-install WARN install No prebuilt binaries found (target=6.1.12 runtime=electron arch=x64 libc= platform=darwin)
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/tl/szr40tn97_q9jb_ylcrxt_4w0000gn/T/apm-install-dir-2020931-1647-65g17y.un6ck/node_modules/platformio-ide-terminal/node_modules/node-pty-prebuilt-multiarch
gyp ERR! node -v v12.4.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/tl/szr40tn97_q9jb_ylcrxt_4w0000gn/T/apm-install-dir-2020931-1647-65g17y.un6ck/package.json'
npm WARN apm-install-dir-2020931-1647-65g17y.un6ck No description
npm WARN apm-install-dir-2020931-1647-65g17y.un6ck No repository field.
npm WARN apm-install-dir-2020931-1647-65g17y.un6ck No README data
npm WARN apm-install-dir-2020931-1647-65g17y.un6ck No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/derickmoncado/.atom/.apm/_logs/2020-10-31T20_26_31_907Z-debug.log
```

**Reproduces how often:** 
100%

### Versions

```
> atom --version
1.52.0
```
```
> apm --version
```
OS name and version:
Platformio-ide-terminal version:
2.10.0

**Comment by ivankravets** [comment]
Fixed in https://github.com/platformio/platformio-atom-ide-terminal/releases/tag/v2.10.1

Please update `platformio-ide-terminal` to the latest version.
