### ISSUE TITLE
platformio-ide-terminal not installing

### ISSUE THREAD

**Issue by pronoym99** [platformio/platformio-atom-ide-terminal#955]
- [ ] I have reset Atom to defaults prior to submitting a report.
- [x] I have not reset Atom to defaults prior to submitting a report.

### Description

The platformio-ide-terminal is not getting installed properly for the past month or so. Following steps describe how to reproduce the issue.

### Steps to reproduce

1. Go to cmd prompt
2. Type in ``` apm install platformio-ide-terminal ``` 

**Expected behaviour:** To install platformio-ide-terminal

**Actual behaviour:** platformio-ide-terminal doesn't get installed and produces the resultant output/error log.

**Reproduces how often:** 100 %

### Versions

```
> atom --version
 Atom    : 1.52.0
Electron: 6.1.12
Chrome  : 76.0.3809.146
Node    : 12.4.0
```
```
> apm --version
apm  2.5.2
npm  6.14.8
node 12.4.0 x64
atom 1.52.0
python 3.8.1
git 2.29.2.windows.1
visual studio
```
OS name and version: Windows 10 Pro 64 - bit (10.0, Build 19041)

Platformio-ide-terminal version:  

- Current version - None
- Expected version after installation - v2.10.0

#### Output log generated

```
Installing platformio-ide-terminal to C:\Users\<username>\.atom\packages failed

> node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install C:\Users\<username>\AppData\Local\Temp\apm-install-dir-2020105-15296-12aownk.g9o\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch
> prebuild-install || node scripts/install.js


C:\Users\<username>\AppData\Local\Temp\apm-install-dir-2020105-15296-12aownk.g9o\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch>if not defined npm_config_node_gyp (node "C:\Users\<username>\AppData\Local\atom\app-1.52.0\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\<username>\AppData\Local\atom\app-1.52.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )

prebuild-install WARN install No prebuilt binaries found (target=6.1.12 runtime=electron arch=x64 libc= platform=win32)
gyp ERR! find VS
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS checking VS2019 (16.7.30330.147) found at:
gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community"
gyp ERR! find VS - "Visual Studio C++ core features" missing
gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS looking for Visual Studio 2013
gyp ERR! find VS - not found
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\<username>\AppData\Local\atom\app-1.52.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at C:\Users\<username>\AppData\Local\atom\app-1.52.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at C:\Users\<username>\AppData\Local\atom\app-1.52.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
gyp ERR! stack     at C:\Users\<username>\AppData\Local\atom\app-1.52.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Users\<username>\AppData\Local\atom\app-1.52.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:297:5)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command "C:\\Users\\<username>\\AppData\\Local\\atom\\app-1.52.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\<username>\\AppData\\Local\\atom\\app-1.52.0\\resources\\app\\apm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\<username>\AppData\Local\Temp\apm-install-dir-2020105-15296-12aownk.g9o\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch
gyp ERR! node -v v12.4.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\<username>\AppData\Local\Temp\apm-install-dir-2020105-15296-12aownk.g9o\package.json'
npm WARN apm-install-dir-2020105-15296-12aownk.g9o No description
npm WARN apm-install-dir-2020105-15296-12aownk.g9o No repository field.
npm WARN apm-install-dir-2020105-15296-12aownk.g9o No README data
npm WARN apm-install-dir-2020105-15296-12aownk.g9o No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\<username>\.atom\.apm\_logs\2020-11-05T04_38_42_099Z-debug.log
```

**Comment by ivankravets** [comment]
Fixed in https://github.com/platformio/platformio-atom-ide-terminal/releases/tag/v2.10.1

Please update `platformio-ide-terminal` to the latest version.
