### ISSUE TITLE
Cannot install packages on clean install of atom

### ISSUE THREAD

**Issue by ccpalmer** [platformio/platformio-atom-ide-terminal#971]
- [x] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Description

Clean install, first time opened, trying to install a package but it fails.

### Steps to reproduce

1. clean install on Catalina 10.15.7
2. move to Applications folder
3. Start atom
4. install package platform IDE Terminal
5. runs for a bit then fails, sometimes with errors sometimes without.

**Expected behavior:** 
successful install

**Actual behavior:** 
install button returns to its initial state
no messages the last several times I tried this.

**Reproduces how often:** 
100%

### Versions
. 

```
Atom    : 1.53.0
Electron: 6.1.12
Chrome  : 76.0.3809.146
Node    : 12.4.0

```

```

apm  2.5.2
npm  6.14.8
node 12.4.0 x64
atom 1.53.0
python 2.7.16
git 2.24.3

```
OS name and version: Mac OS catalina 10.15.7
Platformio-ide-terminal version: platformio-ide-terminal 2.10.0

**Comment by ccpalmer** [comment]
Tried again using apm and got these errors:

```
[~] $ apm install platformio-ide-terminal
Installing platformio-ide-terminal to /Users/ccpalmer/.atom/packages ✗

> node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install /private/var/folders/f0/9_c4f1913l9_25pkfks44ggw0000gn/T/apm-install-dir-20201018-1855-pr2xm8.wnxz/node_modules/platformio-ide-terminal/node_modules/node-pty-prebuilt-multiarch
> prebuild-install || node scripts/install.js


prebuild-install WARN install No prebuilt binaries found (target=6.1.12 runtime=electron arch=x64 libc= platform=darwin)
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/f0/9_c4f1913l9_25pkfks44ggw0000gn/T/apm-install-dir-20201018-1855-pr2xm8.wnxz/node_modules/platformio-ide-terminal/node_modules/node-pty-prebuilt-multiarch
gyp ERR! node -v v12.4.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/f0/9_c4f1913l9_25pkfks44ggw0000gn/T/apm-install-dir-20201018-1855-pr2xm8.wnxz/package.json'
npm WARN apm-install-dir-20201018-1855-pr2xm8.wnxz No description
npm WARN apm-install-dir-20201018-1855-pr2xm8.wnxz No repository field.
npm WARN apm-install-dir-20201018-1855-pr2xm8.wnxz No README data
npm WARN apm-install-dir-20201018-1855-pr2xm8.wnxz No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ccpalmer/.atom/.apm/_logs/2020-11-19T02_37_32_046Z-debug.log

[~] $
```

**Comment by ivankravets** [comment]
Fixed in https://github.com/platformio/platformio-atom-ide-terminal/releases/tag/v2.10.1

Please update `platformio-ide-terminal` to the latest version.
